const fs = require("fs");

const NL = "\n";
const path = "C:/Users/Dell/Desktop/campus Os/2026-04-20-you-are-a-senior-full-stack-2/apps/web/src/app/resume-checker/page.tsx";

const joinChar = String.fromCharCode(10);

const lines = [];
lines.push('"use client";');
lines.push('import { useState } from "react";');
lines.push('import { AppShell } from "@/components/app/app-shell";');
lines.push('');
lines.push('const GROQ_KEY = process.env.NEXT_PUBLIC_GROQ_API_KEY;');
lines.push('');
lines.push('async function analyzeResume(text, role) {');
lines.push('  const targetRole = role || "Software Engineer";');
lines.push('  const jsonFormat = {"score":75,"verdict":"summary","strengths":["s1","s2"],"missing":["m1","m2"],"companies":[{"name":"Google","role":"Intern","match":60,"reason":"why"}],"roadmap":[{"week":"Week 1-2","task":"Learn X","resources":"resource"}],"ats_tips":["tip1","tip2"]};');
lines.push('  const promptText = "You are an expert ATS resume analyzer. Analyze this resume for the role: " + targetRole + ". Resume: " + text + " Reply ONLY in this exact JSON format: " + JSON.stringify(jsonFormat);');
lines.push('  const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {');
lines.push('    method: "POST",');
lines.push('    headers: { "Content-Type": "application/json", "Authorization": "Bearer " + GROQ_KEY },');
lines.push('    body: JSON.stringify({ model: "llama-3.3-70b-versatile", messages: [{ role: "user", content: promptText }], max_tokens: 1024 }),');
lines.push('  });');
lines.push('  const data = await res.json();');
lines.push('  if (data.error) throw new Error(data.error.message);');
lines.push('  const raw = (data.choices && data.choices[0] && data.choices[0].message && data.choices[0].message.content) || "";');
lines.push('  return JSON.parse(raw.replace(/```json/g, "").replace(/```/g, "").trim());');
lines.push('}');
lines.push('');
lines.push('export default function ResumeCheckerPage() {');
lines.push('  const [text, setText] = useState("");');
lines.push('  const [role, setRole] = useState("");');
lines.push('  const [result, setResult] = useState(null);');
lines.push('  const [loading, setLoading] = useState(false);');
lines.push('  const [error, setError] = useState("");');
lines.push('');
lines.push('  const handleFile = (e) => {');
lines.push('    const file = e.target.files && e.target.files[0];');
lines.push('    if (!file) return;');
lines.push('    const reader = new FileReader();');
lines.push('    reader.onload = (ev) => setText(ev.target.result);');
lines.push('    reader.readAsText(file);');
lines.push('  };');
lines.push('');
lines.push('  const run = async () => {');
lines.push('    if (!text.trim()) { setError("Please paste your resume text first."); return; }');
lines.push('    if (!GROQ_KEY) { setError("API key missing! Check .env.local file"); return; }');
lines.push('    setError(""); setLoading(true); setResult(null);');
lines.push('    try { setResult(await analyzeResume(text, role)); }');
lines.push('    catch (e) { setError(e.message); }');
lines.push('    setLoading(false);');
lines.push('  };');
lines.push('');
lines.push('  const col = (s) => s >= 75 ? "text-green-400" : s >= 50 ? "text-yellow-400" : "text-red-400";');
lines.push('  const bgc = (s) => s >= 75 ? "bg-green-400" : s >= 50 ? "bg-yellow-400" : "bg-red-400";');
lines.push('');
lines.push('  const downloadReport = () => {');
lines.push('    const sep = String.fromCharCode(10);');
lines.push('    const parts = ["CampusOS Resume Report", "Score: " + result.score + "/100", "Verdict: " + result.verdict, "", "Strengths:"];');
lines.push('    (result.strengths || []).forEach(function(s) { parts.push("- " + s); });');
lines.push('    parts.push("");');
lines.push('    parts.push("Missing Skills:");');
lines.push('    (result.missing || []).forEach(function(m) { parts.push("- " + m); });');
lines.push('    parts.push("");');
lines.push('    parts.push("Roadmap:");');
lines.push('    (result.roadmap || []).forEach(function(r) { parts.push(r.week + ": " + r.task); });');
lines.push('    const blob = new Blob([parts.join(sep)]);');
lines.push('    const a = document.createElement("a");');
lines.push('    a.href = URL.createObjectURL(blob);');
lines.push('    a.download = "resume-report.txt";');
lines.push('    a.click();');
lines.push('  };');
lines.push('');
lines.push('  return (');
lines.push('    <AppShell activePath="/resume-checker">');
lines.push('      <div className="rounded-[2rem] border border-slate-200/80 bg-white/70 p-6 shadow-[0_25px_80px_rgba(15,23,42,0.08)] backdrop-blur dark:border-white/10 dark:bg-white/5">');
lines.push('        <div className="mb-6">');
lines.push('          <h1 className="text-xl font-bold text-slate-900 dark:text-white">Resume Checker</h1>');
lines.push('          <p className="text-slate-500 dark:text-slate-400 text-sm mt-1">Get AI score, skill gaps, company matches and a learning roadmap</p>');
lines.push('        </div>');
lines.push('        <div className="space-y-4 mb-6">');
lines.push('          <div>');
lines.push('            <label className="text-slate-500 dark:text-slate-400 text-xs mb-2 block font-medium">Upload Resume (.txt)</label>');
lines.push('            <input type="file" accept=".txt" onChange={handleFile} className="w-full bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-xl px-4 py-3 text-slate-600 dark:text-slate-300 text-sm cursor-pointer file:mr-4 file:py-1 file:px-4 file:rounded-full file:border-0 file:bg-cyan-600 file:text-white file:text-xs" />');
lines.push('          </div>');
lines.push('          <div className="text-center text-slate-400 text-xs">OR paste resume text below</div>');
lines.push('          <textarea rows={6} value={text} onChange={(e) => setText(e.target.value)} placeholder="Paste your full resume text here..." className="w-full bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-xl p-4 text-slate-700 dark:text-slate-300 text-sm resize-none focus:outline-none focus:border-cyan-500 transition-colors" />');
lines.push('          <input value={role} onChange={(e) => setRole(e.target.value)} placeholder="Target role (e.g. Frontend Developer)" className="w-full bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-xl px-4 py-3 text-slate-700 dark:text-slate-300 text-sm focus:outline-none focus:border-cyan-500 transition-colors" />');
lines.push('          {error && <div className="bg-red-500/10 border border-red-500/30 rounded-xl p-3"><p className="text-red-400 text-sm">{error}</p></div>}');
lines.push('          <button onClick={run} disabled={loading} className="w-full bg-cyan-600 hover:bg-cyan-500 disabled:opacity-50 text-white font-semibold py-3 rounded-xl text-sm transition-all duration-200">{loading ? "Analyzing..." : "Analyze My Resume"}</button>');
lines.push('        </div>');
lines.push('        {loading && (<div className="text-center py-12"><div className="w-10 h-10 border-2 border-cyan-500 border-t-transparent rounded-full animate-spin mx-auto mb-4" /><p className="text-cyan-500 font-medium text-sm">AI is reading your resume...</p></div>)}');
lines.push('        {result && (');
lines.push('          <div className="space-y-4 mt-2">');
lines.push('            <div className="flex flex-col md:flex-row gap-6 items-center bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl p-6">');
lines.push('              <div className="text-center">');
lines.push('                <div className={col(result.score) + " text-6xl font-black"}>{result.score}</div>');
lines.push('                <div className="text-slate-400 text-xs mt-1">Score / 100</div>');
lines.push('                <div className="w-28 h-1.5 bg-slate-200 dark:bg-slate-700 rounded-full mt-3 mx-auto overflow-hidden">');
lines.push('                  <div className={bgc(result.score) + " h-full rounded-full"} style={{ width: result.score + "%" }} />');
lines.push('                </div>');
lines.push('              </div>');
lines.push('              <div><p className="text-slate-400 text-xs uppercase tracking-wider mb-1">AI Verdict</p><p className="text-slate-800 dark:text-white font-semibold">{result.verdict}</p></div>');
lines.push('            </div>');
lines.push('            <div className="grid md:grid-cols-2 gap-4">');
lines.push('              <div className="bg-green-500/5 border border-green-500/20 rounded-2xl p-4">');
lines.push('                <h3 className="text-green-500 font-semibold mb-3 text-xs uppercase tracking-wider">Strengths</h3>');
lines.push('                {(result.strengths || []).map((s, i) => <p key={i} className="text-slate-600 dark:text-slate-300 text-sm mb-2">+ {s}</p>)}');
lines.push('              </div>');
lines.push('              <div className="bg-red-500/5 border border-red-500/20 rounded-2xl p-4">');
lines.push('                <h3 className="text-red-500 font-semibold mb-3 text-xs uppercase tracking-wider">Missing Skills</h3>');
lines.push('                {(result.missing || []).map((m, i) => <p key={i} className="text-slate-600 dark:text-slate-300 text-sm mb-2">- {m}</p>)}');
lines.push('              </div>');
lines.push('            </div>');
lines.push('            <div className="bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl p-5">');
lines.push('              <h3 className="text-slate-700 dark:text-white font-semibold mb-4 text-xs uppercase tracking-wider">Company Matches</h3>');
lines.push('              {(result.companies || []).map((c, i) => (');
lines.push('                <div key={i} className="flex items-center gap-3 bg-white dark:bg-white/5 rounded-xl p-3 mb-2 border border-slate-100 dark:border-white/5">');
lines.push('                  <div className="w-9 h-9 rounded-full bg-cyan-500/20 border border-cyan-500/30 flex items-center justify-center text-cyan-500 font-bold text-sm flex-shrink-0">{c.name && c.name[0]}</div>');
lines.push('                  <div className="flex-1 min-w-0"><div className="text-slate-800 dark:text-white font-medium text-sm">{c.name} - {c.role}</div><div className="text-slate-400 text-xs mt-0.5">{c.reason}</div></div>');
lines.push('                  <div className={col(c.match) + " font-bold flex-shrink-0"}>{c.match}%</div>');
lines.push('                </div>');
lines.push('              ))}');
lines.push('            </div>');
lines.push('            <div className="bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl p-5">');
lines.push('              <h3 className="text-slate-700 dark:text-white font-semibold mb-4 text-xs uppercase tracking-wider">Learning Roadmap</h3>');
lines.push('              {(result.roadmap || []).map((r, i) => (');
lines.push('                <div key={i} className="flex gap-3 mb-4">');
lines.push('                  <div className="flex flex-col items-center">');
lines.push('                    <div className="w-7 h-7 rounded-full bg-cyan-600/20 border border-cyan-500/30 flex items-center justify-center text-cyan-500 text-xs font-bold flex-shrink-0">{i + 1}</div>');
lines.push('                    {i < result.roadmap.length - 1 && <div className="w-px flex-1 bg-cyan-500/20 mt-1" />}');
lines.push('                  </div>');
lines.push('                  <div className="pb-2"><div className="text-cyan-500 text-xs font-medium mb-0.5">{r.week}</div><div className="text-slate-800 dark:text-white font-medium text-sm mb-0.5">{r.task}</div><div className="text-slate-400 text-xs">{r.resources}</div></div>');
lines.push('                </div>');
lines.push('              ))}');
lines.push('            </div>');
lines.push('            <div className="bg-amber-500/5 border border-amber-500/20 rounded-2xl p-4">');
lines.push('              <h3 className="text-amber-500 font-semibold mb-3 text-xs uppercase tracking-wider">ATS Tips</h3>');
lines.push('              {(result.ats_tips || []).map((t, i) => <p key={i} className="text-slate-600 dark:text-slate-300 text-sm mb-2">- {t}</p>)}');
lines.push('            </div>');
lines.push('            <div className="flex gap-3">');
lines.push('              <button onClick={() => { setResult(null); setText(""); setRole(""); }} className="flex-1 border border-slate-200 dark:border-white/10 hover:border-cyan-500/50 text-slate-600 dark:text-slate-300 font-medium py-3 rounded-xl text-sm transition-all">Analyze Another</button>');
lines.push('              <button onClick={downloadReport} className="flex-1 bg-cyan-600 hover:bg-cyan-500 text-white font-medium py-3 rounded-xl text-sm transition-all">Download Report</button>');
lines.push('            </div>');
lines.push('          </div>');
lines.push('        )}');
lines.push('      </div>');
lines.push('    </AppShell>');
lines.push('  );');
lines.push('}');

fs.writeFileSync(path, lines.join(String.fromCharCode(10)), "utf8");
console.log("Done! File written successfully.");
