const fs = require("fs");

const lines = [];
lines.push('"use client";');
lines.push('import { LoaderCircle, ShieldCheck, ShieldX, GraduationCap, AlertCircle, CheckCircle } from "lucide-react";');
lines.push('import Link from "next/link";');
lines.push('import { useRouter } from "next/navigation";');
lines.push('import { FormEvent, useState } from "react";');
lines.push('import { Logo } from "@/components/shared/logo";');
lines.push('import { ThemeToggle } from "@/components/shared/theme-toggle";');
lines.push('import { registerUserWithPassword } from "@/lib/auth";');
lines.push('import { validateCollegeEmail, isPersonalEmail } from "@/lib/colleges";');
lines.push('');
lines.push('export default function SignupPage() {');
lines.push('  const router = useRouter();');
lines.push('  const [loading, setLoading] = useState(false);');
lines.push('  const [error, setError] = useState("");');
lines.push('  const [emailStatus, setEmailStatus] = useState(null);');
lines.push('  const [form, setForm] = useState({ fullName: "", email: "", password: "", course: "", graduationYear: 2026 });');
lines.push('');
lines.push('  const handleEmailChange = (val) => {');
lines.push('    setForm(f => ({ ...f, email: val }));');
lines.push('    if (val.includes("@")) {');
lines.push('      if (isPersonalEmail(val)) {');
lines.push('        setEmailStatus({ valid: false, message: "Personal emails not allowed. Use your college email.", college: null });');
lines.push('      } else {');
lines.push('        const result = validateCollegeEmail(val);');
lines.push('        if (result.isValid) {');
lines.push('          setEmailStatus({ valid: true, message: "Verified: " + result.college.name + " • " + result.college.location, college: result.college });');
lines.push('        } else if (val.split("@")[1]?.includes(".")) {');
lines.push('          setEmailStatus({ valid: false, message: result.error, college: null });');
lines.push('        } else {');
lines.push('          setEmailStatus(null);');
lines.push('        }');
lines.push('      }');
lines.push('    } else {');
lines.push('      setEmailStatus(null);');
lines.push('    }');
lines.push('  };');
lines.push('');
lines.push('  const onSubmit = async (event: FormEvent<HTMLFormElement>) => {');
lines.push('    event.preventDefault();');
lines.push('    if (!emailStatus || !emailStatus.valid) { setError("Please use a valid authorized college email address."); return; }');
lines.push('    setLoading(true); setError("");');
lines.push('    try {');
lines.push('      registerUserWithPassword({ fullName: form.fullName, email: form.email, collegeName: emailStatus.college?.name || "", collegeVerified: true, collegeDomain: form.email.split("@")[1], course: form.course, graduationYear: form.graduationYear }, form.password);');
lines.push('      router.push("/dashboard");');
lines.push('    } catch (e: any) {');
lines.push('      setError(e.message);');
lines.push('    } finally {');
lines.push('      setLoading(false);');
lines.push('    }');
lines.push('  };');
lines.push('');
lines.push('  return (');
lines.push('    <div className="min-h-screen bg-[radial-gradient(circle_at_top,_rgba(14,165,233,0.18),_transparent_36%),linear-gradient(180deg,#f8fbff_0%,#eef4ff_100%)] px-6 py-8 dark:bg-[radial-gradient(circle_at_top,_rgba(14,165,233,0.16),_transparent_28%),linear-gradient(180deg,#020617_0%,#07111f_100%)]">');
lines.push('      <div className="mx-auto flex max-w-6xl items-center justify-between"><Logo /><ThemeToggle /></div>');
lines.push('      <div className="mx-auto mt-10 grid max-w-6xl gap-8 lg:grid-cols-[1fr_0.9fr]">');
lines.push('');
lines.push('        <form onSubmit={onSubmit} className="rounded-[2.2rem] border border-slate-200/80 bg-white/75 p-8 shadow-[0_25px_80px_rgba(15,23,42,0.08)] backdrop-blur dark:border-white/10 dark:bg-white/5 space-y-5">');
lines.push('          <div>');
lines.push('            <h1 className="text-3xl font-bold text-slate-950 dark:text-white">Create Student Account</h1>');
lines.push('            <p className="text-slate-400 text-sm mt-1">Only authorized Indian college students can register</p>');
lines.push('          </div>');
lines.push('');
lines.push('          <div>');
lines.push('            <label className="text-slate-500 text-xs font-semibold mb-1.5 block">Full Name</label>');
lines.push('            <input value={form.fullName} onChange={e => setForm(f => ({ ...f, fullName: e.target.value }))} placeholder="Your full name" required');
lines.push('              className="w-full rounded-2xl border border-slate-200 bg-slate-50/80 px-4 py-3 text-slate-800 dark:text-white outline-none dark:border-white/10 dark:bg-white/6 focus:border-cyan-500 transition-colors text-sm" />');
lines.push('          </div>');
lines.push('');
lines.push('          <div>');
lines.push('            <label className="text-slate-500 text-xs font-semibold mb-1.5 block flex items-center gap-1">');
lines.push('              <GraduationCap className="w-3.5 h-3.5" /> College Email <span className="text-red-500">*</span>');
lines.push('              <span className="text-slate-400 font-normal">(must be official college email)</span>');
lines.push('            </label>');
lines.push('            <div className="relative">');
lines.push('              <input value={form.email} onChange={e => handleEmailChange(e.target.value)} placeholder="yourname@college.ac.in" required type="email"');
lines.push('                className={"w-full rounded-2xl border px-4 py-3 text-slate-800 dark:text-white outline-none dark:bg-white/6 focus:border-cyan-500 transition-colors text-sm pr-10 " + (emailStatus ? (emailStatus.valid ? "border-green-500/50 bg-green-500/5 dark:border-green-500/30" : "border-red-500/50 bg-red-500/5 dark:border-red-500/30") : "border-slate-200 bg-slate-50/80 dark:border-white/10")} />');
lines.push('              {emailStatus && (');
lines.push('                <div className="absolute right-3 top-1/2 -translate-y-1/2">');
lines.push('                  {emailStatus.valid ? <CheckCircle className="w-5 h-5 text-green-500" /> : <ShieldX className="w-5 h-5 text-red-500" />}');
lines.push('                </div>');
lines.push('              )}');
lines.push('            </div>');
lines.push('            {emailStatus && (');
lines.push('              <div className={"mt-2 flex items-start gap-2 rounded-xl px-3 py-2 text-xs " + (emailStatus.valid ? "bg-green-500/10 text-green-600" : "bg-red-500/10 text-red-500")}>');
lines.push('                {emailStatus.valid ? <ShieldCheck className="w-3.5 h-3.5 flex-shrink-0 mt-0.5" /> : <ShieldX className="w-3.5 h-3.5 flex-shrink-0 mt-0.5" />}');
lines.push('                <span>{emailStatus.message}</span>');
lines.push('              </div>');
lines.push('            )}');
lines.push('          </div>');
lines.push('');
lines.push('          <div>');
lines.push('            <label className="text-slate-500 text-xs font-semibold mb-1.5 block">Password <span className="text-slate-400 font-normal">(min 8 characters)</span></label>');
lines.push('            <input value={form.password} onChange={e => setForm(f => ({ ...f, password: e.target.value }))} placeholder="Create strong password" required type="password"');
lines.push('              className="w-full rounded-2xl border border-slate-200 bg-slate-50/80 px-4 py-3 text-slate-800 dark:text-white outline-none dark:border-white/10 dark:bg-white/6 focus:border-cyan-500 transition-colors text-sm" />');
lines.push('          </div>');
lines.push('');
lines.push('          <div className="grid grid-cols-2 gap-4">');
lines.push('            <div>');
lines.push('              <label className="text-slate-500 text-xs font-semibold mb-1.5 block">Course</label>');
lines.push('              <input value={form.course} onChange={e => setForm(f => ({ ...f, course: e.target.value }))} placeholder="e.g. B.Tech CSE, MCA"');
lines.push('                className="w-full rounded-2xl border border-slate-200 bg-slate-50/80 px-4 py-3 text-slate-800 dark:text-white outline-none dark:border-white/10 dark:bg-white/6 focus:border-cyan-500 transition-colors text-sm" />');
lines.push('            </div>');
lines.push('            <div>');
lines.push('              <label className="text-slate-500 text-xs font-semibold mb-1.5 block">Graduation Year</label>');
lines.push('              <select value={form.graduationYear} onChange={e => setForm(f => ({ ...f, graduationYear: Number(e.target.value) }))}');
lines.push('                className="w-full rounded-2xl border border-slate-200 bg-slate-50/80 px-4 py-3 text-slate-800 dark:text-white outline-none dark:border-white/10 dark:bg-white/6 focus:border-cyan-500 transition-colors text-sm">');
lines.push('                {[2025, 2026, 2027, 2028, 2029].map(y => <option key={y} value={y}>{y}</option>)}');
lines.push('              </select>');
lines.push('            </div>');
lines.push('          </div>');
lines.push('');
lines.push('          {error && (');
lines.push('            <div className="bg-red-500/10 border border-red-500/30 rounded-2xl p-4 flex items-start gap-3">');
lines.push('              <AlertCircle className="w-4 h-4 text-red-500 flex-shrink-0 mt-0.5" />');
lines.push('              <p className="text-red-500 text-sm">{error}</p>');
lines.push('            </div>');
lines.push('          )}');
lines.push('');
lines.push('          <button type="submit" disabled={loading || !emailStatus || !emailStatus.valid}');
lines.push('            className="w-full inline-flex items-center justify-center gap-2 rounded-2xl bg-slate-950 px-5 py-4 text-sm font-semibold text-white dark:bg-white dark:text-slate-950 disabled:opacity-50 transition-all">');
lines.push('            {loading ? <><LoaderCircle className="h-4 w-4 animate-spin" />Creating account...</> : <><ShieldCheck className="h-4 w-4" />Create Verified Student Account</>}');
lines.push('          </button>');
lines.push('          <p className="text-center text-sm text-slate-500">Already have an account? <Link href="/login" className="font-semibold text-cyan-600 dark:text-cyan-300">Login</Link></p>');
lines.push('        </form>');
lines.push('');
lines.push('        <div className="space-y-4">');
lines.push('          <div className="rounded-[2.2rem] border border-white/20 bg-[linear-gradient(180deg,#0f172a,#0b334d)] p-7 text-white">');
lines.push('            <div className="flex items-center gap-3 mb-4">');
lines.push('              <ShieldCheck className="w-6 h-6 text-cyan-400" />');
lines.push('              <p className="text-sm font-bold uppercase tracking-widest text-cyan-200">Verified Access Only</p>');
lines.push('            </div>');
lines.push('            <h2 className="text-2xl font-bold mb-4">Why college email only?</h2>');
lines.push('            <div className="space-y-3">');
lines.push('              {["Ensures only genuine students access the platform", "Prevents fake accounts and spam", "Builds a trusted verified student community", "Your college identity adds credibility to your profile"].map(item => (');
lines.push('                <div key={item} className="flex items-start gap-2">');
lines.push('                  <CheckCircle className="w-4 h-4 text-green-400 flex-shrink-0 mt-0.5" />');
lines.push('                  <p className="text-slate-200 text-sm">{item}</p>');
lines.push('                </div>');
lines.push('              ))}');
lines.push('            </div>');
lines.push('          </div>');
lines.push('');
lines.push('          <div className="rounded-[2rem] border border-slate-200/80 bg-white/70 p-6 dark:border-white/10 dark:bg-white/5">');
lines.push('            <h3 className="text-slate-900 dark:text-white font-bold text-sm mb-3 flex items-center gap-2"><GraduationCap className="w-4 h-4 text-cyan-500" />Sample Authorized Emails</h3>');
lines.push('            <div className="space-y-2">');
lines.push('              {["yourname@lpu.in", "rollno@vit.ac.in", "name@iitb.ac.in", "student@thapar.edu", "yourname@chandigarh.edu.in", "roll@bits-pilani.ac.in"].map(ex => (');
lines.push('                <div key={ex} className="flex items-center gap-2 bg-green-500/5 border border-green-500/20 rounded-xl px-3 py-2">');
lines.push('                  <CheckCircle className="w-3.5 h-3.5 text-green-500 flex-shrink-0" />');
lines.push('                  <code className="text-green-600 dark:text-green-400 text-xs font-mono">{ex}</code>');
lines.push('                </div>');
lines.push('              ))}');
lines.push('            </div>');
lines.push('            <div className="mt-3 space-y-2">');
lines.push('              {["yourname@gmail.com", "student@yahoo.com"].map(ex => (');
lines.push('                <div key={ex} className="flex items-center gap-2 bg-red-500/5 border border-red-500/20 rounded-xl px-3 py-2">');
lines.push('                  <ShieldX className="w-3.5 h-3.5 text-red-500 flex-shrink-0" />');
lines.push('                  <code className="text-red-500 text-xs font-mono line-through">{ex}</code>');
lines.push('                  <span className="text-red-400 text-xs">Not allowed</span>');
lines.push('                </div>');
lines.push('              ))}');
lines.push('            </div>');
lines.push('          </div>');
lines.push('');
lines.push('          <div className="rounded-[2rem] border border-amber-500/20 bg-amber-500/5 p-5">');
lines.push('            <p className="text-amber-600 dark:text-amber-400 text-xs font-semibold mb-1">Your college not listed?</p>');
lines.push('            <p className="text-slate-500 text-xs">We are adding more colleges regularly. Contact your college administration to get your institution added to CampusOS.</p>');
lines.push('          </div>');
lines.push('        </div>');
lines.push('      </div>');
lines.push('    </div>');
lines.push('  );');
lines.push('}');

fs.writeFileSync(
  "C:/Users/Dell/Desktop/campus Os/2026-04-20-you-are-a-senior-full-stack-2/apps/web/src/app/signup/page.tsx",
  lines.join("\n"), "utf8"
);
console.log("Signup page updated!");
