const fs = require("fs");

const code = [
'"use client";',
'import { LoaderCircle } from "lucide-react";',
'import Link from "next/link";',
'import { useRouter } from "next/navigation";',
'import { FormEvent, useState } from "react";',
'import { Logo } from "@/components/shared/logo";',
'import { ThemeToggle } from "@/components/shared/theme-toggle";',
'import { loginUser } from "@/lib/auth";',
'',
'export default function LoginPage() {',
'  const router = useRouter();',
'  const [email, setEmail] = useState("");',
'  const [password, setPassword] = useState("");',
'  const [loading, setLoading] = useState(false);',
'  const [error, setError] = useState("");',
'',
'  const onSubmit = async (event: FormEvent<HTMLFormElement>) => {',
'    event.preventDefault();',
'    setLoading(true);',
'    setError("");',
'    try {',
'      loginUser(email, password);',
'      router.push("/dashboard");',
'    } catch (e: any) {',
'      setError(e.message);',
'    } finally {',
'      setLoading(false);',
'    }',
'  };',
'',
'  return (',
'    <div className="min-h-screen bg-[radial-gradient(circle_at_top,_rgba(34,211,238,0.18),_transparent_36%),linear-gradient(180deg,#f8fbff_0%,#eef4ff_100%)] px-6 py-8 dark:bg-[radial-gradient(circle_at_top,_rgba(34,211,238,0.16),_transparent_28%),linear-gradient(180deg,#020617_0%,#07111f_100%)]">',
'      <div className="mx-auto flex max-w-6xl items-center justify-between">',
'        <Logo />',
'        <ThemeToggle />',
'      </div>',
'      <div className="mx-auto mt-10 grid max-w-6xl gap-8 lg:grid-cols-[1fr_0.95fr]">',
'        <div className="rounded-[2.2rem] border border-white/20 bg-[linear-gradient(180deg,#0f172a,#0b334d)] p-8 text-white shadow-[0_40px_120px_rgba(15,23,42,0.28)]">',
'          <p className="text-sm font-semibold uppercase tracking-[0.28em] text-cyan-200">Welcome back</p>',
'          <h1 className="mt-5 text-5xl font-semibold tracking-tight">Enter the student ecosystem with one trusted login.</h1>',
'          <p className="mt-5 max-w-xl text-base leading-8 text-slate-200">Access your digital student ID, AI notes finder, verified jobs, and scam defense stack from one clean workspace.</p>',
'          <div className="mt-8 p-4 bg-white/5 border border-white/10 rounded-2xl">',
'            <p className="text-cyan-300 text-sm font-semibold mb-2">Demo Account</p>',
'            <p className="text-slate-300 text-xs">Email: aarav.sharma@lpu.edu.in</p>',
'            <p className="text-slate-300 text-xs">Password: CampusOS@123</p>',
'            <p className="text-slate-400 text-xs mt-2">Or create your own account via Signup</p>',
'          </div>',
'        </div>',
'        <form onSubmit={onSubmit} className="rounded-[2.2rem] border border-slate-200/80 bg-white/75 p-8 shadow-[0_25px_80px_rgba(15,23,42,0.08)] backdrop-blur dark:border-white/10 dark:bg-white/5">',
'          <h2 className="text-3xl font-semibold text-slate-950 dark:text-white">Login</h2>',
'          <div className="mt-6 space-y-4">',
'            <input className="w-full rounded-2xl border border-slate-200 bg-slate-50/80 px-4 py-3 outline-none dark:border-white/10 dark:bg-white/6 text-slate-800 dark:text-white" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="College email" type="email" required />',
'            <input type="password" className="w-full rounded-2xl border border-slate-200 bg-slate-50/80 px-4 py-3 outline-none dark:border-white/10 dark:bg-white/6 text-slate-800 dark:text-white" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" required />',
'          </div>',
'          {error && <div className="mt-4 bg-red-500/10 border border-red-500/30 rounded-xl p-3"><p className="text-red-500 text-sm">{error}</p></div>}',
'          <button type="submit" className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 px-5 py-4 text-sm font-semibold text-white dark:bg-white dark:text-slate-950">',
'            {loading && <LoaderCircle className="h-4 w-4 animate-spin" />}',
'            {loading ? "Signing in..." : "Login to CampusOS"}',
'          </button>',
'          <p className="mt-6 text-sm text-slate-500 dark:text-slate-400">New here? <Link href="/signup" className="font-semibold text-cyan-600 dark:text-cyan-300">Create your account</Link></p>',
'        </form>',
'      </div>',
'    </div>',
'  );',
'}',
].join("\n");

fs.writeFileSync(
  "C:/Users/Dell/Desktop/campus Os/2026-04-20-you-are-a-senior-full-stack-2/apps/web/src/app/login/page.tsx",
  code, "utf8"
);
console.log("login page fixed!");
