const fs = require("fs");

const code = [
'"use client";',
'import { useEffect, useState } from "react";',
'import { AppShell } from "@/components/app/app-shell";',
'import { getUser } from "@/lib/auth";',
'import { Briefcase, MapPin, CheckCircle, AlertCircle, Filter, ExternalLink } from "lucide-react";',
'',
'const ALL_JOBS = [',
'  { id: "job_1", title: "Frontend Engineer Intern", company: "NovaStack Labs", location: "Remote", type: "Internship", stipend: "25,000/month", verified: true, postedAt: "Today", applyUrl: "https://linkedin.com/jobs", tags: ["React", "Next.js", "Tailwind", "JavaScript"], description: "Design polished student-facing experiences with a strong review and mentorship culture.", skillsRequired: ["React", "Next.js", "TypeScript", "UI Design"], keywords: ["frontend", "react", "javascript", "web", "ui", "ux", "next"] },',
'  { id: "job_2", title: "Backend Developer Trainee", company: "SafeLane Tech", location: "Bengaluru", type: "Full-time", stipend: "6.5 LPA", verified: true, postedAt: "Yesterday", applyUrl: "https://linkedin.com/jobs", tags: ["Node.js", "Express", "MongoDB"], description: "Build robust APIs, tools, and scalable backend workflows for growth-stage products.", skillsRequired: ["Node.js", "Express", "MongoDB", "REST APIs"], keywords: ["backend", "node", "express", "mongodb", "api", "server"] },',
'  { id: "job_3", title: "Python Developer Intern", company: "DataVerse AI", location: "Remote", type: "Internship", stipend: "20,000/month", verified: true, postedAt: "Today", applyUrl: "https://linkedin.com/jobs", tags: ["Python", "Django", "REST API"], description: "Build Python-based APIs and data pipelines for an AI-first product team.", skillsRequired: ["Python", "Django", "REST APIs"], keywords: ["python", "django", "backend", "data", "ml", "ai"] },',
'  { id: "job_4", title: "Data Analyst Intern", company: "InsightMetrics", location: "Hybrid", type: "Internship", stipend: "18,000/month", verified: true, postedAt: "2 days ago", applyUrl: "https://linkedin.com/jobs", tags: ["Python", "SQL", "Excel", "Tableau"], description: "Analyze datasets, build dashboards and help teams make data-driven decisions.", skillsRequired: ["Python", "SQL", "Data Analysis", "Excel"], keywords: ["data", "analyst", "sql", "python", "excel", "analytics", "bi"] },',
'  { id: "job_5", title: "Full Stack Developer Intern", company: "BuildFast Studio", location: "Remote", type: "Internship", stipend: "22,000/month", verified: true, postedAt: "Today", applyUrl: "https://linkedin.com/jobs", tags: ["React", "Node.js", "MongoDB", "Express"], description: "Work on complete product features from database to UI in a fast-paced startup.", skillsRequired: ["React", "Node.js", "MongoDB", "JavaScript"], keywords: ["fullstack", "full stack", "mern", "react", "node", "mongodb"] },',
'  { id: "job_6", title: "Machine Learning Intern", company: "NeuralBridge", location: "Bengaluru", type: "Internship", stipend: "25,000/month", verified: true, postedAt: "3 days ago", applyUrl: "https://linkedin.com/jobs", tags: ["Python", "TensorFlow", "ML", "Deep Learning"], description: "Implement ML models, run experiments and optimize AI pipelines for production.", skillsRequired: ["Python", "Machine Learning", "TensorFlow", "NumPy"], keywords: ["ml", "machine learning", "ai", "deep learning", "python", "data science"] },',
'  { id: "job_7", title: "DevOps Engineer Intern", company: "CloudStack India", location: "Remote", type: "Internship", stipend: "20,000/month", verified: true, postedAt: "Today", applyUrl: "https://linkedin.com/jobs", tags: ["Docker", "AWS", "Linux", "CI/CD"], description: "Set up deployment pipelines, manage cloud infra and automate dev workflows.", skillsRequired: ["Docker", "AWS", "Linux", "Git"], keywords: ["devops", "docker", "aws", "cloud", "linux", "ci/cd", "deployment"] },',
'  { id: "job_8", title: "Android Developer Intern", company: "AppCraft Labs", location: "Noida", type: "Internship", stipend: "15,000/month", verified: false, postedAt: "4 days ago", applyUrl: "https://linkedin.com/jobs", tags: ["Kotlin", "Android", "Java"], description: "Build and maintain Android features for a student-focused mobile app.", skillsRequired: ["Kotlin", "Android", "Java", "Mobile"], keywords: ["android", "mobile", "kotlin", "java", "app"] },',
'  { id: "job_9", title: "Java Developer Trainee", company: "TechBridge Corp", location: "Pune", type: "Full-time", stipend: "4.5 LPA", verified: true, postedAt: "2 days ago", applyUrl: "https://linkedin.com/jobs", tags: ["Java", "Spring Boot", "MySQL"], description: "Develop enterprise Java applications with Spring Boot and REST APIs.", skillsRequired: ["Java", "Spring Boot", "MySQL", "OOP"], keywords: ["java", "spring", "backend", "enterprise", "oop"] },',
'  { id: "job_10", title: "UI/UX Design Intern", company: "PixelForge", location: "Remote", type: "Internship", stipend: "12,000/month", verified: true, postedAt: "Today", applyUrl: "https://linkedin.com/jobs", tags: ["Figma", "UI Design", "Wireframing"], description: "Design intuitive interfaces and user flows for B2B SaaS products.", skillsRequired: ["Figma", "UI Design", "Prototyping", "UX Research"], keywords: ["ui", "ux", "design", "figma", "product", "wireframe"] },',
'];',
'',
'function getMatchedJobs(targetRole: string, resumeStrengths: string[]) {',
'  if (!targetRole && (!resumeStrengths || resumeStrengths.length === 0)) return ALL_JOBS;',
'  const roleWords = (targetRole || "").toLowerCase().split(/\s+/);',
'  const strengthWords = (resumeStrengths || []).join(" ").toLowerCase().split(/\s+/);',
'  const allKeywords = [...roleWords, ...strengthWords];',
'  const scored = ALL_JOBS.map(job => {',
'    let score = 0;',
'    allKeywords.forEach(kw => {',
'      if (kw.length < 2) return;',
'      job.keywords.forEach(jk => { if (jk.includes(kw) || kw.includes(jk)) score += 2; });',
'      job.tags.forEach(t => { if (t.toLowerCase().includes(kw)) score += 1; });',
'      if (job.title.toLowerCase().includes(kw)) score += 3;',
'    });',
'    return { ...job, score };',
'  });',
'  return scored.sort((a, b) => b.score - a.score);',
'}',
'',
'export default function JobsPage() {',
'  const [user, setUser] = useState<any>(null);',
'  const [jobs, setJobs] = useState(ALL_JOBS);',
'  const [filter, setFilter] = useState("all");',
'  const [isFiltered, setIsFiltered] = useState(false);',
'',
'  useEffect(() => {',
'    const u = getUser();',
'    setUser(u);',
'    if (u) {',
'      const targetRole = u.resumeVerdict || "";',
'      const strengths = u.resumeStrengths || [];',
'      if (targetRole || strengths.length > 0) {',
'        setJobs(getMatchedJobs(targetRole, strengths));',
'        setIsFiltered(true);',
'      }',
'    }',
'  }, []);',
'',
'  const filtered = filter === "all" ? jobs : jobs.filter(j => j.type.toLowerCase().includes(filter));',
'',
'  return (',
'    <AppShell activePath="/jobs">',
'      <section className="space-y-5">',
'        <div className="rounded-[2rem] border border-slate-200/80 bg-white/75 p-6 shadow-[0_25px_80px_rgba(15,23,42,0.08)] dark:border-white/10 dark:bg-white/5">',
'          <p className="text-sm font-semibold uppercase tracking-[0.22em] text-cyan-600 dark:text-cyan-300">Verified Opportunities</p>',
'          <h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950 dark:text-white">Jobs and internships with actual trust signals.</h1>',
'          {isFiltered && user && (',
'            <div className="mt-4 flex items-center gap-2 bg-cyan-500/10 border border-cyan-500/20 rounded-2xl px-4 py-3">',
'              <Filter className="w-4 h-4 text-cyan-500 flex-shrink-0" />',
'              <p className="text-cyan-600 dark:text-cyan-400 text-sm">',
'                Showing jobs matched to <span className="font-bold">{user.fullName}</span>\'s resume skills and target role',
'              </p>',
'            </div>',
'          )}',
'          {!isFiltered && (',
'            <div className="mt-4 flex items-center gap-2 bg-amber-500/10 border border-amber-500/20 rounded-2xl px-4 py-3">',
'              <AlertCircle className="w-4 h-4 text-amber-500 flex-shrink-0" />',
'              <p className="text-amber-600 dark:text-amber-400 text-sm">',
'                <a href="/resume-checker" className="font-bold underline">Analyze your resume</a> to get personalized job recommendations',
'              </p>',
'            </div>',
'          )}',
'          <div className="flex flex-wrap gap-2 mt-4">',
'            {["all", "internship", "full-time", "fellowship"].map(f => (',
'              <button key={f} onClick={() => setFilter(f)}',
'                className={"px-4 py-1.5 rounded-full text-xs font-semibold border transition-all " + (filter === f ? "bg-slate-950 text-white border-slate-950 dark:bg-white dark:text-slate-950" : "border-slate-200 text-slate-500 hover:border-slate-400 dark:border-white/10 dark:text-slate-400")}>',
'                {f.charAt(0).toUpperCase() + f.slice(1)}',
'              </button>',
'            ))}',
'          </div>',
'        </div>',
'',
'        <div className="grid gap-4">',
'          {filtered.map((job, idx) => (',
'            <article key={job.id} className="rounded-[1.8rem] border border-slate-200/80 bg-white/75 p-6 dark:border-white/10 dark:bg-white/5 hover:border-slate-300 dark:hover:border-white/20 transition-all">',
'              <div className="flex flex-wrap items-start justify-between gap-4">',
'                <div className="flex-1 min-w-0">',
'                  <div className="flex items-center gap-2 flex-wrap">',
'                    {idx === 0 && isFiltered && <span className="text-xs bg-cyan-500/15 text-cyan-500 border border-cyan-500/20 px-2 py-0.5 rounded-full font-bold">Best Match</span>}',
'                    {idx === 1 && isFiltered && <span className="text-xs bg-violet-500/15 text-violet-500 border border-violet-500/20 px-2 py-0.5 rounded-full font-bold">Strong Match</span>}',
'                    <h2 className="text-xl font-bold text-slate-950 dark:text-white">{job.title}</h2>',
'                  </div>',
'                  <p className="mt-1 text-sm text-slate-500 dark:text-slate-400 flex items-center gap-2">',
'                    <Briefcase className="w-3.5 h-3.5" />{job.company}',
'                    <MapPin className="w-3.5 h-3.5 ml-1" />{job.location} • {job.type} • {job.postedAt}',
'                  </p>',
'                </div>',
'                <div className="flex items-center gap-2 flex-shrink-0">',
'                  <span className="rounded-full bg-cyan-500/10 border border-cyan-500/20 px-3 py-1 text-xs font-semibold text-cyan-700 dark:text-cyan-300">',
'                    {job.stipend}',
'                  </span>',
'                  <span className={"rounded-full px-3 py-1 text-xs font-semibold flex items-center gap-1 " + (job.verified ? "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 border border-emerald-500/20" : "bg-amber-500/10 text-amber-700 dark:text-amber-300 border border-amber-500/20")}>',
'                    {job.verified ? <CheckCircle className="w-3 h-3" /> : <AlertCircle className="w-3 h-3" />}',
'                    {job.verified ? "Verified" : "Review manually"}',
'                  </span>',
'                </div>',
'              </div>',
'              <p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{job.description}</p>',
'              <div className="mt-4 flex flex-wrap items-center justify-between gap-3">',
'                <div className="flex flex-wrap gap-2">',
'                  {job.tags.map(tag => (',
'                    <span key={tag} className="rounded-full border border-slate-200 bg-white dark:border-white/10 dark:bg-white/5 px-3 py-1 text-xs text-slate-600 dark:text-slate-400">',
'                      {tag}',
'                    </span>',
'                  ))}',
'                </div>',
'                <a href={job.applyUrl} target="_blank" rel="noopener noreferrer"',
'                  className="inline-flex items-center gap-2 bg-slate-950 dark:bg-white text-white dark:text-slate-950 px-4 py-2 rounded-xl text-xs font-semibold hover:opacity-90 transition-all">',
'                  <ExternalLink className="w-3.5 h-3.5" />Apply Now',
'                </a>',
'              </div>',
'            </article>',
'          ))}',
'        </div>',
'      </section>',
'    </AppShell>',
'  );',
'}',
].join("\n");

fs.writeFileSync(
  "C:/Users/Dell/Desktop/campus Os/2026-04-20-you-are-a-senior-full-stack-2/apps/web/src/app/jobs/page.tsx",
  code, "utf8"
);
console.log("Jobs page fixed with smart matching!");
