const fs = require("fs");

const path = "C:/Users/Dell/Desktop/campus Os/2026-04-20-you-are-a-senior-full-stack-2/apps/web/src/data/mock.ts";
let content = fs.readFileSync(path, "utf8");

const oldResources = `export const mockResources: ResourceItem[] = [
  {
    id: "res_1",
    title: "DSA Crash Notes for Placements",
    type: "notes",
    subject: "Data Structures & Algorithms",
    description: "Revision-oriented notes built for coding rounds, patterns, and complexity recall.",
    url: "https://example.com/resources/dsa-crash-notes",
    tags: ["placements", "dsa", "algorithms", "revision"],
    level: "intermediate",
    source: "CampusOS Curated",
    offlineAvailable: true,
    semanticScore: 95,
  },
  {
    id: "res_2",
    title: "System Design for Students",
    type: "pdf",
    subject: "System Design",
    description: "A beginner-to-intermediate handbook on APIs, scaling, queues, and databases.",
    url: "https://example.com/resources/system-design-students.pdf",
    tags: ["system design", "backend", "architecture"],
    level: "beginner",
    source: "Verified Mentor Pack",
    offlineAvailable: true,
    semanticScore: 88,
  },
  {
    id: "res_3",
    title: "DBMS One-Shot Placement Video",
    type: "video",
    subject: "DBMS",
    description: "One focused video for SQL, joins, indexing, normalization, and transactions.",
    url: "https://example.com/resources/dbms-one-shot",
    tags: ["dbms", "sql", "video", "placements"],
    level: "intermediate",
    source: "Creator Partner",
    offlineAvailable: false,
    semanticScore: 82,
  },
  {
    id: "res_4",
    title: "React Interview Handbook",
    type: "link",
    subject: "Frontend Development",
    description: "Performance patterns, architecture answers, and practical frontend interview prep.",
    url: "https://example.com/resources/react-handbook",
    tags: ["react", "frontend", "interviews", "javascript"],
    level: "advanced",
    source: "Open Learning Hub",
    offlineAvailable: true,
    semanticScore: 90,
  },
];`;

const newResources = `export const mockResources: ResourceItem[] = [
  {
    id: "res_1",
    title: "DSA Crack Sheet - Striver",
    type: "notes",
    subject: "Data Structures & Algorithms",
    description: "Most important DSA problems and patterns for placements. Covers arrays, trees, graphs, DP and more.",
    url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/",
    tags: ["placements", "dsa", "algorithms", "revision"],
    level: "intermediate",
    source: "TakeUForward",
    offlineAvailable: false,
    semanticScore: 95,
  },
  {
    id: "res_2",
    title: "OS Notes - Gate Smashers",
    type: "notes",
    subject: "Operating Systems",
    description: "Complete OS notes covering process management, memory, scheduling, deadlocks and file systems.",
    url: "https://www.youtube.com/playlist?list=PLxCzCOWd7aiGz9donHRrE9I3Mwn6XdP8p",
    tags: ["os", "operating system", "gate", "placements"],
    level: "intermediate",
    source: "Gate Smashers",
    offlineAvailable: false,
    semanticScore: 90,
  },
  {
    id: "res_3",
    title: "DBMS Complete Notes - InterviewBit",
    type: "link",
    subject: "Database Management Systems",
    description: "SQL queries, joins, indexing, normalization, transactions and ACID properties explained clearly.",
    url: "https://www.interviewbit.com/dbms-interview-questions/",
    tags: ["dbms", "sql", "placements", "interview"],
    level: "intermediate",
    source: "InterviewBit",
    offlineAvailable: false,
    semanticScore: 88,
  },
  {
    id: "res_4",
    title: "Computer Networks Notes - GeeksforGeeks",
    type: "link",
    subject: "Computer Networks",
    description: "OSI model, TCP/IP, subnetting, routing protocols and socket programming for interviews.",
    url: "https://www.geeksforgeeks.org/computer-network-tutorials/",
    tags: ["networks", "cn", "tcp", "placements"],
    level: "beginner",
    source: "GeeksforGeeks",
    offlineAvailable: false,
    semanticScore: 85,
  },
  {
    id: "res_5",
    title: "OOP Concepts - Java Brains",
    type: "link",
    subject: "Object Oriented Programming",
    description: "Classes, objects, inheritance, polymorphism, encapsulation and abstraction with real examples.",
    url: "https://www.geeksforgeeks.org/object-oriented-programming-oops-concept-in-java/",
    tags: ["oops", "java", "oop", "placements"],
    level: "beginner",
    source: "GeeksforGeeks",
    offlineAvailable: false,
    semanticScore: 87,
  },
  {
    id: "res_6",
    title: "System Design Primer",
    type: "link",
    subject: "System Design",
    description: "Complete system design guide covering scalability, load balancing, caching, databases and microservices.",
    url: "https://github.com/donnemartin/system-design-primer",
    tags: ["system design", "backend", "architecture", "senior"],
    level: "advanced",
    source: "GitHub - donnemartin",
    offlineAvailable: false,
    semanticScore: 92,
  },
  {
    id: "res_7",
    title: "Aptitude Shortcuts - IndiaBIX",
    type: "link",
    subject: "Quantitative Aptitude",
    description: "Shortcuts and tricks for quantitative aptitude, logical reasoning and verbal ability for campus placements.",
    url: "https://www.indiabix.com/",
    tags: ["aptitude", "reasoning", "placements", "campus"],
    level: "beginner",
    source: "IndiaBIX",
    offlineAvailable: false,
    semanticScore: 80,
  },
  {
    id: "res_8",
    title: "React Complete Guide - Scrimba",
    type: "link",
    subject: "Frontend Development",
    description: "Hands-on React course covering hooks, state management, routing and building real projects.",
    url: "https://scrimba.com/learn/learnreact",
    tags: ["react", "frontend", "javascript", "web"],
    level: "intermediate",
    source: "Scrimba",
    offlineAvailable: false,
    semanticScore: 86,
  },
];`;

content = content.replace(oldResources, newResources);
fs.writeFileSync(path, content, "utf8");
console.log("mock.ts updated!");
