const fs = require("fs");

const code = [
'"use client";',
'import { LoaderCircle } from "lucide-react";',
'import Link from "next/link";',
'import { useRouter } from "next/navigation";',
'import { FormEvent, useState } from "react";',
'import { Logo } from "@/components/shared/logo";',
'import { ThemeToggle } from "@/components/shared/theme-toggle";',
'import { registerUserWithPassword } from "@/lib/auth";',
'',
'export default function SignupPage() {',
'  const router = useRouter();',
'  const [loading, setLoading] = useState(false);',
'  const [error, setError] = useState("");',
'  const [form, setForm] = useState({',
'    fullName: "",',
'    email: "",',
'    password: "",',
'    collegeName: "",',
'    course: "",',
'    graduationYear: 2027,',
'  });',
'',
'  const onSubmit = async (event: FormEvent<HTMLFormElement>) => {',
'    event.preventDefault();',
'    setLoading(true);',
'    setError("");',
'    try {',
'      registerUserWithPassword({',
'        fullName: form.fullName,',
'        email: form.email,',
'        collegeName: form.collegeName,',
'        course: form.course,',
'        graduationYear: form.graduationYear,',
'      }, form.password);',
'      router.push("/dashboard");',
'    } catch (e: any) {',
'      setError(e.message);',
'    } finally {',
'      setLoading(false);',
'    }',
'  };',
'',
'  return (',
'    <div className="min-h-screen bg-[radial-gradient(circle_at_top,_rgba(14,165,233,0.18),_transparent_36%),linear-gradient(180deg,#f8fbff_0%,#eef4ff_100%)] px-6 py-8 dark:bg-[radial-gradient(circle_at_top,_rgba(14,165,233,0.16),_transparent_28%),linear-gradient(180deg,#020617_0%,#07111f_100%)]">',
'      <div className="mx-auto flex max-w-6xl items-center justify-between">',
'        <Logo />',
'        <ThemeToggle />',
'      </div>',
'      <div className="mx-auto mt-10 grid max-w-6xl gap-8 lg:grid-cols-[0.9fr_1.1fr]">',
'        <form onSubmit={onSubmit} className="rounded-[2.2rem] border border-slate-200/80 bg-white/75 p-8 shadow-[0_25px_80px_rgba(15,23,42,0.08)] backdrop-blur dark:border-white/10 dark:bg-white/5">',
'          <h1 className="text-3xl font-semibold text-slate-950 dark:text-white">Create your verified student identity</h1>',
'          <div className="mt-6 grid gap-4 md:grid-cols-2">',
'            {([["Full name", "fullName", "text"], ["College email", "email", "email"], ["Password", "password", "password"], ["College name", "collegeName", "text"], ["Course (e.g. MCA)", "course", "text"]] as [string,string,string][]).map(([label, key, type]) => (',
'              <input key={key} type={type} value={form[key as keyof typeof form] as string} onChange={(e) => setForm(f => ({ ...f, [key]: e.target.value }))} placeholder={label} required className="w-full rounded-2xl border border-slate-200 bg-slate-50/80 px-4 py-3 outline-none dark:border-white/10 dark:bg-white/6 text-slate-800 dark:text-white" />',
'            ))}',
'            <input type="number" value={form.graduationYear} onChange={(e) => setForm(f => ({ ...f, graduationYear: Number(e.target.value) }))} placeholder="Graduation year" className="w-full rounded-2xl border border-slate-200 bg-slate-50/80 px-4 py-3 outline-none dark:border-white/10 dark:bg-white/6 text-slate-800 dark:text-white" />',
'          </div>',
'          {error && <div className="mt-4 bg-red-500/10 border border-red-500/30 rounded-xl p-3"><p className="text-red-500 text-sm">{error}</p></div>}',
'          <button type="submit" className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 px-5 py-4 text-sm font-semibold text-white dark:bg-white dark:text-slate-950">',
'            {loading && <LoaderCircle className="h-4 w-4 animate-spin" />}',
'            {loading ? "Creating account..." : "Create CampusOS account"}',
'          </button>',
'          <p className="mt-6 text-sm text-slate-500 dark:text-slate-400">Already have an account? <Link href="/login" className="font-semibold text-cyan-600 dark:text-cyan-300">Login</Link></p>',
'        </form>',
'        <div className="rounded-[2.2rem] border border-white/20 bg-[linear-gradient(180deg,#0f172a,#0b334d)] p-8 text-white shadow-[0_40px_120px_rgba(15,23,42,0.28)]">',
'          <p className="text-sm font-semibold uppercase tracking-[0.28em] text-cyan-200">What unlocks after signup</p>',
'          <div className="mt-6 space-y-5">',
'            {["Verified digital ID with your real name and college", "AI Resume Analyzer saves your score and progress", "Scam detection for fake jobs and internships", "Verified opportunity board plus bookmarks"].map((item) => (',
'              <div key={item} className="rounded-[1.4rem] border border-white/10 bg-white/8 px-5 py-4 text-sm text-slate-200 flex items-center gap-3">',
'                <span className="text-cyan-400">?</span>{item}',
'              </div>',
'            ))}',
'          </div>',
'          <div className="mt-8 p-4 bg-cyan-500/10 border border-cyan-500/20 rounded-2xl">',
'            <p className="text-cyan-300 text-xs font-semibold">Your data stays on your device. No backend required.</p>',
'          </div>',
'        </div>',
'      </div>',
'    </div>',
'  );',
'}',
].join("\n");

fs.writeFileSync(
  "C:/Users/Dell/Desktop/campus Os/2026-04-20-you-are-a-senior-full-stack-2/apps/web/src/app/signup/page.tsx",
  code, "utf8"
);
console.log("signup page fixed!");
