const fs = require("fs");
const path = "C:/Users/Dell/Desktop/campus Os/2026-04-20-you-are-a-senior-full-stack-2/apps/web/src/components/app/scam-checker-panel.tsx";

const lines = [];
lines.push('"use client";');
lines.push('import { useState } from "react";');
lines.push('import { ShieldCheck, ShieldX, AlertTriangle, CheckCircle, XCircle, AlertCircle, Eye, Lock, Globe, MessageSquare, DollarSign, Clock, User, Phone, ExternalLink, Copy, RotateCcw } from "lucide-react";');
lines.push('');
lines.push('const GROQ_KEY = process.env.NEXT_PUBLIC_GROQ_API_KEY;');
lines.push('');
lines.push('async function analyzeScam(text) {');
lines.push('  const fmt = {');
lines.push('    verdict: "SCAM",');
lines.push('    confidence: 85,');
lines.push('    risk_level: "HIGH",');
lines.push('    summary: "2-3 sentence overall analysis of why this is safe or a scam",');
lines.push('    what_to_do_now: "Exact next steps the student should take right now",');
lines.push('    red_flags: [{ flag: "flag title", detail: "detailed explanation of why this is suspicious", severity: "HIGH" }],');
lines.push('    green_flags: [{ flag: "flag title", detail: "why this seems legitimate" }],');
lines.push('    domain_analysis: { verdict: "SUSPICIOUS", detail: "analysis of email domain, website, contact info used" },');
lines.push('    language_analysis: { verdict: "SUSPICIOUS", detail: "analysis of urgency, grammar, pressure tactics in the message" },');
lines.push('    payment_analysis: { verdict: "SCAM", detail: "any payment requests, fees, deposits mentioned" },');
lines.push('    identity_analysis: { verdict: "SAFE", detail: "analysis of who is reaching out, their credentials" },');
lines.push('    safe_percentage: 15,');
lines.push('    scam_percentage: 85,');
lines.push('    similar_scams: ["Type of known scam this resembles"],');
lines.push('    verification_steps: ["Step 1 to verify if this is real", "Step 2"],');
lines.push('    report_to: ["Where to report this scam if it is fake"]');
lines.push('  };');
lines.push('  const prompt = "You are an expert cybersecurity analyst specializing in student job scams in India. Analyze this job posting or message for scam indicators. Be thorough and specific. Text to analyze: " + text + " Reply ONLY in this exact JSON format with no extra text: " + JSON.stringify(fmt);');
lines.push('  const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {');
lines.push('    method: "POST",');
lines.push('    headers: { "Content-Type": "application/json", "Authorization": "Bearer " + GROQ_KEY },');
lines.push('    body: JSON.stringify({ model: "llama-3.3-70b-versatile", messages: [{ role: "user", content: prompt }], max_tokens: 2048 }),');
lines.push('  });');
lines.push('  const data = await res.json();');
lines.push('  if (data.error) throw new Error(data.error.message);');
lines.push('  const raw = (data.choices[0].message.content || "").replace(/```json/g, "").replace(/```/g, "").trim();');
lines.push('  return JSON.parse(raw);');
lines.push('}');
lines.push('');
lines.push('const EXAMPLES = [');
lines.push('  { label: "Fake Internship", text: "Urgent internship offer! You have been selected. Pay Rs 2000 registration fee today. Contact HR on WhatsApp: 9876543210. hrteam@gmail.com. Joining in 24 hours or offer expires." },');
lines.push('  { label: "Real Job Post", text: "Tata Consultancy Services is hiring Software Developer Trainees. Apply at careers.tcs.com. Eligibility: B.Tech/MCA 2024/2025 batch. CGPA above 6. No fees required. Interview process: Online test, Technical round, HR round." },');
lines.push('  { label: "Suspicious LinkedIn", text: "Hi, I saw your profile and you are perfect for our opening. We offer work from home job, Rs 50000 per month, just 2 hours daily. No experience needed. Send your Aadhar and bank details to start immediately." },');
lines.push('];');
lines.push('');
lines.push('function RiskMeter({ score }) {');
lines.push('  const color = score >= 70 ? "text-red-500" : score >= 40 ? "text-amber-500" : "text-green-500";');
lines.push('  const bg = score >= 70 ? "bg-red-500" : score >= 40 ? "bg-amber-500" : "bg-green-500";');
lines.push('  const label = score >= 70 ? "HIGH RISK" : score >= 40 ? "MEDIUM RISK" : "LOW RISK";');
lines.push('  return (');
lines.push('    <div className="text-center">');
lines.push('      <div className={"text-7xl font-black " + color}>{score}%</div>');
lines.push('      <div className={"text-xs font-bold tracking-widest mt-1 " + color}>{label}</div>');
lines.push('      <div className="w-full h-3 bg-slate-200 dark:bg-slate-700 rounded-full mt-3 overflow-hidden">');
lines.push('        <div className={"h-full rounded-full transition-all duration-1000 " + bg} style={{ width: score + "%" }} />');
lines.push('      </div>');
lines.push('      <div className="flex justify-between text-xs text-slate-400 mt-1">');
lines.push('        <span>Safe</span><span>Risky</span><span>Scam</span>');
lines.push('      </div>');
lines.push('    </div>');
lines.push('  );');
lines.push('}');
lines.push('');
lines.push('function AnalysisCard({ icon: Icon, title, verdict, detail, color }) {');
lines.push('  const colors = {');
lines.push('    safe: "bg-green-500/5 border-green-500/20 text-green-500",');
lines.push('    suspicious: "bg-amber-500/5 border-amber-500/20 text-amber-500",');
lines.push('    scam: "bg-red-500/5 border-red-500/20 text-red-500",');
lines.push('  };');
lines.push('  const v = (verdict || "suspicious").toLowerCase();');
lines.push('  const cls = colors[v] || colors.suspicious;');
lines.push('  return (');
lines.push('    <div className={"rounded-2xl border p-4 " + cls.split(" ")[0] + " " + cls.split(" ")[1]}>');
lines.push('      <div className="flex items-center gap-2 mb-2">');
lines.push('        <Icon className={"w-4 h-4 " + cls.split(" ")[2]} />');
lines.push('        <span className={"text-xs font-bold uppercase tracking-wider " + cls.split(" ")[2]}>{title}</span>');
lines.push('        <span className={"ml-auto text-xs font-bold px-2 py-0.5 rounded-full border " + cls}>{verdict}</span>');
lines.push('      </div>');
lines.push('      <p className="text-slate-600 dark:text-slate-300 text-xs leading-relaxed">{detail}</p>');
lines.push('    </div>');
lines.push('  );');
lines.push('}');
lines.push('');
lines.push('export function ScamCheckerPanel() {');
lines.push('  const [input, setInput] = useState("");');
lines.push('  const [result, setResult] = useState(null);');
lines.push('  const [loading, setLoading] = useState(false);');
lines.push('  const [error, setError] = useState("");');
lines.push('  const [copied, setCopied] = useState(false);');
lines.push('');
lines.push('  const analyze = async () => {');
lines.push('    if (!input.trim()) { setError("Paste a job posting or message first."); return; }');
lines.push('    setError(""); setLoading(true); setResult(null);');
lines.push('    try { setResult(await analyzeScam(input)); }');
lines.push('    catch (e) { setError("Error: " + e.message); }');
lines.push('    setLoading(false);');
lines.push('  };');
lines.push('');
lines.push('  const copy = () => {');
lines.push('    if (!result) return;');
lines.push('    const sep = String.fromCharCode(10);');
lines.push('    const parts = ["CampusOS Scam Analysis Report", "========================", "Verdict: " + result.verdict, "Scam Risk: " + result.scam_percentage + "%", "Summary: " + result.summary, "", "RED FLAGS:"];');
lines.push('    (result.red_flags || []).forEach(f => parts.push("- " + f.flag + ": " + f.detail));');
lines.push('    parts.push(""); parts.push("WHAT TO DO NOW:"); parts.push(result.what_to_do_now);');
lines.push('    parts.push(""); parts.push("VERIFICATION STEPS:");');
lines.push('    (result.verification_steps || []).forEach(s => parts.push("- " + s));');
lines.push('    navigator.clipboard.writeText(parts.join(sep));');
lines.push('    setCopied(true);');
lines.push('    setTimeout(() => setCopied(false), 2000);');
lines.push('  };');
lines.push('');
lines.push('  const verdictConfig = {');
lines.push('    SAFE: { icon: ShieldCheck, color: "text-green-500", bg: "bg-green-500/10 border-green-500/30", label: "SAFE" },');
lines.push('    SUSPICIOUS: { icon: AlertTriangle, color: "text-amber-500", bg: "bg-amber-500/10 border-amber-500/30", label: "SUSPICIOUS" },');
lines.push('    SCAM: { icon: ShieldX, color: "text-red-500", bg: "bg-red-500/10 border-red-500/30", label: "SCAM DETECTED" },');
lines.push('  };');
lines.push('  const vc = result ? (verdictConfig[result.verdict] || verdictConfig.SUSPICIOUS) : null;');
lines.push('');
lines.push('  return (');
lines.push('    <div className="space-y-5">');
lines.push('');
lines.push('      <div className="rounded-[2rem] border border-slate-200/80 bg-white/70 p-6 dark:border-white/10 dark:bg-white/5">');
lines.push('        <div className="flex items-center gap-2 mb-4">');
lines.push('          <Eye className="w-4 h-4 text-cyan-500" />');
lines.push('          <span className="text-cyan-600 dark:text-cyan-300 text-xs font-bold uppercase tracking-wider">Quick Examples</span>');
lines.push('        </div>');
lines.push('        <div className="flex flex-wrap gap-2 mb-4">');
lines.push('          {EXAMPLES.map(ex => (');
lines.push('            <button key={ex.label} onClick={() => setInput(ex.text)}');
lines.push('              className="px-3 py-1.5 bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-xl text-xs font-medium text-slate-600 dark:text-slate-400 hover:border-cyan-500/40 hover:text-cyan-600 transition-all">');
lines.push('              {ex.label}');
lines.push('            </button>');
lines.push('          ))}');
lines.push('        </div>');
lines.push('        <textarea rows={6} value={input} onChange={e => setInput(e.target.value)}');
lines.push('          placeholder="Paste the full job posting, WhatsApp message, email, or internship offer here..."');
lines.push('          className="w-full bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl p-4 text-sm text-slate-700 dark:text-slate-300 resize-none focus:outline-none focus:border-cyan-500 transition-colors leading-relaxed" />');
lines.push('        {error && <div className="mt-3 bg-red-500/10 border border-red-500/30 rounded-xl p-3"><p className="text-red-400 text-sm">{error}</p></div>}');
lines.push('        <div className="flex gap-3 mt-4">');
lines.push('          <button onClick={analyze} disabled={loading}');
lines.push('            className="flex-1 bg-slate-950 dark:bg-white hover:opacity-90 disabled:opacity-50 text-white dark:text-slate-950 font-semibold py-3 rounded-2xl text-sm transition-all flex items-center justify-center gap-2">');
lines.push('            {loading ? (<><div className="w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin" />Analyzing deeply...</>) : (<><ShieldX className="w-4 h-4" />Analyze for Scam</>)}');
lines.push('          </button>');
lines.push('          {result && (');
lines.push('            <button onClick={() => { setResult(null); setInput(""); }} className="px-4 py-3 border border-slate-200 dark:border-white/10 rounded-2xl text-slate-500 hover:border-red-500/30 hover:text-red-500 transition-all">');
lines.push('              <RotateCcw className="w-4 h-4" />');
lines.push('            </button>');
lines.push('          )}');
lines.push('        </div>');
lines.push('      </div>');
lines.push('');
lines.push('      {loading && (');
lines.push('        <div className="rounded-[2rem] border border-slate-200/80 bg-white/70 p-12 text-center dark:border-white/10 dark:bg-white/5">');
lines.push('          <div className="w-16 h-16 border-4 border-cyan-500 border-t-transparent rounded-full animate-spin mx-auto mb-6" />');
lines.push('          <p className="text-slate-800 dark:text-white font-bold text-lg mb-2">AI is scanning for scam signals...</p>');
lines.push('          <div className="space-y-2 mt-4 max-w-xs mx-auto">');
lines.push('            {["Checking domain trust signals", "Analyzing language patterns", "Detecting payment requests", "Verifying contact credibility", "Generating safety report"].map((s, i) => (');
lines.push('              <div key={i} className="flex items-center gap-2 text-slate-400 text-sm">');
lines.push('                <div className="w-1.5 h-1.5 bg-cyan-500 rounded-full animate-pulse" style={{ animationDelay: i * 200 + "ms" }} />');
lines.push('                {s}');
lines.push('              </div>');
lines.push('            ))}');
lines.push('          </div>');
lines.push('        </div>');
lines.push('      )}');
lines.push('');
lines.push('      {result && vc && (');
lines.push('        <div className="space-y-5">');
lines.push('');
lines.push('          <div className={"rounded-[2rem] border-2 p-8 " + vc.bg}>');
lines.push('            <div className="flex flex-col md:flex-row gap-8 items-center">');
lines.push('              <div className="text-center flex-shrink-0">');
lines.push('                <vc.icon className={"w-16 h-16 mx-auto mb-4 " + vc.color} />');
lines.push('                <div className={"text-2xl font-black px-6 py-2 rounded-2xl border-2 " + vc.bg + " " + vc.color}>{vc.label}</div>');
lines.push('                <div className="mt-4"><RiskMeter score={result.scam_percentage} /></div>');
lines.push('              </div>');
lines.push('              <div className="flex-1">');
lines.push('                <div className="flex items-center justify-between mb-3 flex-wrap gap-2">');
lines.push('                  <h2 className="text-slate-900 dark:text-white font-bold text-xl">Analysis Summary</h2>');
lines.push('                  <button onClick={copy} className="flex items-center gap-1.5 text-xs border border-slate-200 dark:border-white/10 px-3 py-1.5 rounded-xl text-slate-500 hover:border-cyan-500/30 hover:text-cyan-500 transition-all">');
lines.push('                    <Copy className="w-3.5 h-3.5" />{copied ? "Copied!" : "Copy Report"}');
lines.push('                  </button>');
lines.push('                </div>');
lines.push('                <p className="text-slate-700 dark:text-slate-300 text-sm leading-relaxed mb-4">{result.summary}</p>');
lines.push('                <div className="flex gap-4">');
lines.push('                  <div className="text-center">');
lines.push('                    <div className="text-green-500 font-black text-2xl">{result.safe_percentage}%</div>');
lines.push('                    <div className="text-slate-400 text-xs">Safe signals</div>');
lines.push('                  </div>');
lines.push('                  <div className="w-px bg-slate-200 dark:bg-white/10" />');
lines.push('                  <div className="text-center">');
lines.push('                    <div className="text-red-500 font-black text-2xl">{result.scam_percentage}%</div>');
lines.push('                    <div className="text-slate-400 text-xs">Scam signals</div>');
lines.push('                  </div>');
lines.push('                  <div className="w-px bg-slate-200 dark:bg-white/10" />');
lines.push('                  <div className="text-center">');
lines.push('                    <div className="text-slate-800 dark:text-white font-black text-2xl">{result.red_flags ? result.red_flags.length : 0}</div>');
lines.push('                    <div className="text-slate-400 text-xs">Red flags</div>');
lines.push('                  </div>');
lines.push('                  <div className="w-px bg-slate-200 dark:bg-white/10" />');
lines.push('                  <div className="text-center">');
lines.push('                    <div className="text-slate-800 dark:text-white font-black text-2xl">{result.green_flags ? result.green_flags.length : 0}</div>');
lines.push('                    <div className="text-slate-400 text-xs">Green flags</div>');
lines.push('                  </div>');
lines.push('                </div>');
lines.push('              </div>');
lines.push('            </div>');
lines.push('          </div>');
lines.push('');
lines.push('          <div className={"rounded-[2rem] border-2 p-6 " + (result.scam_percentage >= 70 ? "border-red-500/40 bg-red-500/5" : result.scam_percentage >= 40 ? "border-amber-500/40 bg-amber-500/5" : "border-green-500/40 bg-green-500/5")}>');
lines.push('            <div className="flex items-start gap-3">');
lines.push('              <div className={"w-10 h-10 rounded-2xl flex items-center justify-center flex-shrink-0 " + (result.scam_percentage >= 70 ? "bg-red-500/20" : result.scam_percentage >= 40 ? "bg-amber-500/20" : "bg-green-500/20")}>');
lines.push('                <AlertCircle className={"w-5 h-5 " + (result.scam_percentage >= 70 ? "text-red-500" : result.scam_percentage >= 40 ? "text-amber-500" : "text-green-500")} />');
lines.push('              </div>');
lines.push('              <div>');
lines.push('                <h3 className="text-slate-900 dark:text-white font-bold mb-2">What You Should Do RIGHT NOW</h3>');
lines.push('                <p className="text-slate-700 dark:text-slate-300 text-sm leading-relaxed">{result.what_to_do_now}</p>');
lines.push('              </div>');
lines.push('            </div>');
lines.push('          </div>');
lines.push('');
lines.push('          <div className="grid md:grid-cols-2 gap-5">');
lines.push('            <div className="bg-red-500/5 border border-red-500/20 rounded-2xl p-5">');
lines.push('              <div className="flex items-center gap-2 mb-4">');
lines.push('                <XCircle className="w-4 h-4 text-red-500" />');
lines.push('                <h3 className="text-red-500 font-bold text-sm uppercase tracking-wider">Red Flags Found ({result.red_flags ? result.red_flags.length : 0})</h3>');
lines.push('              </div>');
lines.push('              {result.red_flags && result.red_flags.length > 0 ? result.red_flags.map((f, i) => (');
lines.push('                <div key={i} className="mb-4 bg-red-500/5 border border-red-500/10 rounded-xl p-3">');
lines.push('                  <div className="flex items-center justify-between mb-1">');
lines.push('                    <span className="text-red-500 font-semibold text-sm">{f.flag}</span>');
lines.push('                    <span className={"text-xs font-bold px-2 py-0.5 rounded-full " + (f.severity === "HIGH" ? "bg-red-500/20 text-red-500" : "bg-amber-500/20 text-amber-500")}>{f.severity}</span>');
lines.push('                  </div>');
lines.push('                  <p className="text-slate-600 dark:text-slate-400 text-xs leading-relaxed">{f.detail}</p>');
lines.push('                </div>');
lines.push('              )) : <p className="text-slate-400 text-sm">No red flags detected</p>}');
lines.push('            </div>');
lines.push('            <div className="bg-green-500/5 border border-green-500/20 rounded-2xl p-5">');
lines.push('              <div className="flex items-center gap-2 mb-4">');
lines.push('                <CheckCircle className="w-4 h-4 text-green-500" />');
lines.push('                <h3 className="text-green-500 font-bold text-sm uppercase tracking-wider">Green Flags Found ({result.green_flags ? result.green_flags.length : 0})</h3>');
lines.push('              </div>');
lines.push('              {result.green_flags && result.green_flags.length > 0 ? result.green_flags.map((f, i) => (');
lines.push('                <div key={i} className="mb-4 bg-green-500/5 border border-green-500/10 rounded-xl p-3">');
lines.push('                  <span className="text-green-500 font-semibold text-sm block mb-1">{f.flag}</span>');
lines.push('                  <p className="text-slate-600 dark:text-slate-400 text-xs leading-relaxed">{f.detail}</p>');
lines.push('                </div>');
lines.push('              )) : <p className="text-slate-400 text-sm">No green flags detected</p>}');
lines.push('            </div>');
lines.push('          </div>');
lines.push('');
lines.push('          <div className="grid md:grid-cols-2 gap-4">');
lines.push('            <AnalysisCard icon={Globe} title="Domain Analysis" verdict={result.domain_analysis && result.domain_analysis.verdict} detail={result.domain_analysis && result.domain_analysis.detail} />');
lines.push('            <AnalysisCard icon={MessageSquare} title="Language Analysis" verdict={result.language_analysis && result.language_analysis.verdict} detail={result.language_analysis && result.language_analysis.detail} />');
lines.push('            <AnalysisCard icon={DollarSign} title="Payment Analysis" verdict={result.payment_analysis && result.payment_analysis.verdict} detail={result.payment_analysis && result.payment_analysis.detail} />');
lines.push('            <AnalysisCard icon={User} title="Identity Analysis" verdict={result.identity_analysis && result.identity_analysis.verdict} detail={result.identity_analysis && result.identity_analysis.detail} />');
lines.push('          </div>');
lines.push('');
lines.push('          {result.similar_scams && result.similar_scams.length > 0 && (');
lines.push('            <div className="bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl p-5">');
lines.push('              <h3 className="text-slate-700 dark:text-white font-bold text-sm uppercase tracking-wider mb-3 flex items-center gap-2"><AlertTriangle className="w-4 h-4 text-amber-500" />Similar Known Scams</h3>');
lines.push('              {result.similar_scams.map((s, i) => (');
lines.push('                <div key={i} className="flex items-center gap-2 mb-2">');
lines.push('                  <span className="text-amber-500 text-xs font-bold">•</span>');
lines.push('                  <p className="text-slate-600 dark:text-slate-300 text-sm">{s}</p>');
lines.push('                </div>');
lines.push('              ))}');
lines.push('            </div>');
lines.push('          )}');
lines.push('');
lines.push('          <div className="bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl p-5">');
lines.push('            <h3 className="text-slate-700 dark:text-white font-bold text-sm uppercase tracking-wider mb-4 flex items-center gap-2"><Lock className="w-4 h-4 text-cyan-500" />Steps to Verify if This is Real</h3>');
lines.push('            {(result.verification_steps || []).map((s, i) => (');
lines.push('              <div key={i} className="flex items-start gap-3 mb-3 bg-white dark:bg-white/5 border border-slate-100 dark:border-white/5 rounded-xl p-3">');
lines.push('                <div className="w-6 h-6 rounded-full bg-cyan-500/20 border border-cyan-500/30 flex items-center justify-center text-cyan-500 text-xs font-bold flex-shrink-0">{i + 1}</div>');
lines.push('                <p className="text-slate-600 dark:text-slate-300 text-sm">{s}</p>');
lines.push('              </div>');
lines.push('            ))}');
lines.push('          </div>');
lines.push('');
lines.push('          {result.report_to && result.report_to.length > 0 && (');
lines.push('            <div className="bg-violet-500/5 border border-violet-500/20 rounded-2xl p-5">');
lines.push('              <h3 className="text-violet-600 dark:text-violet-400 font-bold text-sm uppercase tracking-wider mb-4 flex items-center gap-2"><Phone className="w-4 h-4" />Where to Report This Scam</h3>');
lines.push('              {result.report_to.map((r, i) => (');
lines.push('                <div key={i} className="flex items-center gap-2 mb-2">');
lines.push('                  <ExternalLink className="w-3.5 h-3.5 text-violet-500 flex-shrink-0" />');
lines.push('                  <p className="text-slate-600 dark:text-slate-300 text-sm">{r}</p>');
lines.push('                </div>');
lines.push('              ))}');
lines.push('              <div className="mt-4 pt-4 border-t border-violet-500/20">');
lines.push('                <p className="text-violet-600 dark:text-violet-400 text-xs font-semibold">National Cyber Crime Helpline: 1930 | cybercrime.gov.in</p>');
lines.push('              </div>');
lines.push('            </div>');
lines.push('          )}');
lines.push('');
lines.push('          <div className="bg-slate-900 dark:bg-white/5 border border-slate-700 dark:border-white/10 rounded-2xl p-5">');
lines.push('            <h3 className="text-white font-bold text-sm mb-3">Student Safety Reminders</h3>');
lines.push('            <div className="grid md:grid-cols-2 gap-2">');
lines.push('              {[');
lines.push('                "Legitimate companies NEVER ask for registration or security fees",');
lines.push('                "Real HR teams use company email, not Gmail or WhatsApp",');
lines.push('                "No genuine job offer expires in 24 hours",');
lines.push('                "Never share Aadhar, PAN, or bank details before joining",');
lines.push('                "Always verify company on LinkedIn and official website",');
lines.push('                "Call the company directly using numbers from their official site",');
lines.push('              ].map((tip, i) => (');
lines.push('                <div key={i} className="flex items-start gap-2">');
lines.push('                  <span className="text-cyan-400 text-xs mt-0.5 flex-shrink-0">?</span>');
lines.push('                  <p className="text-slate-300 text-xs">{tip}</p>');
lines.push('                </div>');
lines.push('              ))}');
lines.push('            </div>');
lines.push('          </div>');
lines.push('');
lines.push('        </div>');
lines.push('      )}');
lines.push('    </div>');
lines.push('  );');
lines.push('}');

fs.writeFileSync(path, lines.join("\n"), "utf8");
console.log("Scam checker upgraded!");
