const fs = require("fs");

const code = [
'"use client";',
'import { useState } from "react";',
'import { AppShell } from "@/components/app/app-shell";',
'',
'const GROQ_KEY = process.env.NEXT_PUBLIC_GROQ_API_KEY;',
'',
'async function analyzeResume(text, role) {',
'  const targetRole = role || "Software Engineer";',
'  const promptText = "You are an expert ATS resume analyzer. Analyze this resume for the role: " + targetRole + ". Resume content: " + text + ". Reply ONLY in this exact JSON format with no extra text: {" + JSON.stringify({score:75,verdict:"summary",strengths:["s1"],missing:["m1"],companies:[{name:"Google",role:"Intern",match:60,reason:"why"}],roadmap:[{week:"Week 1-2",task:"Learn X",resources:"resource"}],ats_tips:["tip1"]}).slice(1,-1) + "}";',
'',
'  const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {',
'    method: "POST",',
'    headers: {',
'      "Content-Type": "application/json",',
'      "Authorization": "Bearer " + GROQ_KEY,',
'    },',
'    body: JSON.stringify({',
'      model: "llama-3.3-70b-versatile",',
'      messages: [{ role: "user", content: promptText }],',
'      max_tokens: 1024,',
'    }),',
'  });',
'  const data = await res.json();',
'  if (data.error) throw new Error(data.error.message);',
'  const raw = (data.choices && data.choices[0] && data.choices[0].message && data.choices[0].message.content) || "";',
'  const clean = raw.replace(/```json/g, "").replace(/```/g, "").trim();',
'  return JSON.parse(clean);',
'}',
'',
'export default function ResumeCheckerPage() {',
'  const [text, setText] = useState("");',
'  const [role, setRole] = useState("");',
'  const [result, setResult] = useState(null);',
'  const [loading, setLoading] = useState(false);',
'  const [error, setError] = useState("");',
'',
'  const handleFile = (e) => {',
'    const file = e.target.files && e.target.files[0];',
'    if (!file) return;',
'    const reader = new FileReader();',
'    reader.onload = (ev) => setText(ev.target.result);',
'    reader.readAsText(file);',
'  };',
'',
'  const run = async () => {',
'    if (!text.trim()) { setError("Please paste your resume text first."); return; }',
'    if (!GROQ_KEY) { setError("API key missing! Check .env.local file"); return; }',
'    setError(""); setLoading(true); setResult(null);',
'    try {',
'      setResult(await analyzeResume(text, role));',
'    } catch (e) {',
'      setError(e.message);',
'    }',
'    setLoading(false);',
'  };',
'',
'  const col = (s) => s >= 75 ? "text-green-400" : s >= 50 ? "text-yellow-400" : "text-red-400";',
'  const bgc = (s) => s >= 75 ? "bg-green-400" : s >= 50 ? "bg-yellow-400" : "bg-red-400";',
'',
'  const downloadReport = () => {',
'    const lines = [];',
'    lines.push("CampusOS Resume Report");',
'    lines.push("Score: " + result.score + "/100");',
'    lines.push("Verdict: " + result.verdict);',
'    lines.push("");',
'    lines.push("Strengths:");',
'    (result.strengths || []).forEach(function(s) { lines.push("- " + s); });',
'    lines.push("");',
'    lines.push("Missing Skills:");',
'    (result.missing || []).forEach(function(m) { lines.push("- " + m); });',
'    lines.push("");',
'    lines.push("Roadmap:");',
'    (result.roadmap || []).forEach(function(r) { lines.push(r.week + ": " + r.task); });',
'    const blob = new Blob([lines.join("\n")]);',
'    const a = document.createElement("a");',
'    a.href = URL.createObjectURL(blob);',
'    a.download = "resume-report.txt";',
'    a.click();',
'  };',
'',
'  return (',
'    <AppShell activePath="/resume-checker">',
'      <div className="rounded-[2rem] border border-slate-200/80 bg-white/70 p-6 shadow-[0_25px_80px_rgba(15,23,42,0.08)] backdrop-blur dark:border-white/10 dark:bg-white/5">',
'        <div className="mb-6">',
'          <h1 className="text-xl font-bold text-slate-900 dark:text-white">Resume Checker</h1>',
'          <p className="text-slate-500 dark:text-slate-400 text-sm mt-1">Get AI score, skill gaps, company matches and a learning roadmap</p>',
'        </div>',
'        <div className="space-y-4 mb-6">',
'          <div>',
'            <label className="text-slate-500 dark:text-slate-400 text-xs mb-2 block font-medium">Upload Resume (.txt)</label>',
'            <input type="file" accept=".txt" onChange={handleFile} className="w-full bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-xl px-4 py-3 text-slate-600 dark:text-slate-300 text-sm cursor-pointer file:mr-4 file:py-1 file:px-4 file:rounded-full file:border-0 file:bg-cyan-600 file:text-white file:text-xs" />',
'          </div>',
'          <div className="text-center text-slate-400 text-xs">OR paste resume text below</div>',
'          <textarea rows={6} value={text} onChange={(e) => setText(e.target.value)} placeholder="Paste your full resume text here..." className="w-full bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-xl p-4 text-slate-700 dark:text-slate-300 text-sm resize-none focus:outline-none focus:border-cyan-500 transition-colors" />',
'          <input value={role} onChange={(e) => setRole(e.target.value)} placeholder="Target role (e.g. Frontend Developer)" className="w-full bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-xl px-4 py-3 text-slate-700 dark:text-slate-300 text-sm focus:outline-none focus:border-cyan-500 transition-colors" />',
'          {error && <div className="bg-red-500/10 border border-red-500/30 rounded-xl p-3"><p className="text-red-400 text-sm">{error}</p></div>}',
'          <button onClick={run} disabled={loading} className="w-full bg-cyan-600 hover:bg-cyan-500 disabled:opacity-50 text-white font-semibold py-3 rounded-xl text-sm transition-all duration-200">',
'            {loading ? "Analyzing..." : "Analyze My Resume"}',
'          </button>',
'        </div>',
'        {loading && (',
'          <div className="text-center py-12">',
'            <div className="w-10 h-10 border-2 border-cyan-500 border-t-transparent rounded-full animate-spin mx-auto mb-4" />',
'            <p className="text-cyan-500 font-medium text-sm">AI is reading your resume...</p>',
'          </div>',
'        )}',
'        {result && (',
'          <div className="space-y-4 mt-2">',
'            <div className="flex flex-col md:flex-row gap-6 items-center bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl p-6">',
'              <div className="text-center">',
'                <div className={col(result.score) + " text-6xl font-black"}>{result.score}</div>',
'                <div className="text-slate-400 text-xs mt-1">Score / 100</div>',
'                <div className="w-28 h-1.5 bg-slate-200 dark:bg-slate-700 rounded-full mt-3 mx-auto overflow-hidden">',
'                  <div className={bgc(result.score) + " h-full rounded-full"} style={{ width: result.score + "%" }} />',
'                </div>',
'              </div>',
'              <div>',
'                <p className="text-slate-400 text-xs uppercase tracking-wider mb-1">AI Verdict</p>',
'                <p className="text-slate-800 dark:text-white font-semibold">{result.verdict}</p>',
'              </div>',
'            </div>',
'            <div className="grid md:grid-cols-2 gap-4">',
'              <div className="bg-green-500/5 border border-green-500/20 rounded-2xl p-4">',
'                <h3 className="text-green-500 font-semibold mb-3 text-xs uppercase tracking-wider">Strengths</h3>',
'                {(result.strengths || []).map((s, i) => <p key={i} className="text-slate-600 dark:text-slate-300 text-sm mb-2">+ {s}</p>)}',
'              </div>',
'              <div className="bg-red-500/5 border border-red-500/20 rounded-2xl p-4">',
'                <h3 className="text-red-500 font-semibold mb-3 text-xs uppercase tracking-wider">Missing Skills</h3>',
'                {(result.missing || []).map((m, i) => <p key={i} className="text-slate-600 dark:text-slate-300 text-sm mb-2">- {m}</p>)}',
'              </div>',
'            </div>',
'            <div className="bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl p-5">',
'              <h3 className="text-slate-700 dark:text-white font-semibold mb-4 text-xs uppercase tracking-wider">Company Matches</h3>',
'              {(result.companies || []).map((c, i) => (',
'                <div key={i} className="flex items-center gap-3 bg-white dark:bg-white/5 rounded-xl p-3 mb-2 border border-slate-100 dark:border-white/5">',
'                  <div className="w-9 h-9 rounded-full bg-cyan-500/20 border border-cyan-500/30 flex items-center justify-center text-cyan-500 font-bold text-sm flex-shrink-0">{c.name && c.name[0]}</div>',
'                  <div className="flex-1 min-w-0">',
'                    <div className="text-slate-800 dark:text-white font-medium text-sm">{c.name} - {c.role}</div>',
'                    <div className="text-slate-400 text-xs mt-0.5">{c.reason}</div>',
'                  </div>',
'                  <div className={col(c.match) + " font-bold flex-shrink-0"}>{c.match}%</div>',
'                </div>',
'              ))}',
'            </div>',
'            <div className="bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl p-5">',
'              <h3 className="text-slate-700 dark:text-white font-semibold mb-4 text-xs uppercase tracking-wider">Learning Roadmap</h3>',
'              {(result.roadmap || []).map((r, i) => (',
'                <div key={i} className="flex gap-3 mb-4">',
'                  <div className="flex flex-col items-center">',
'                    <div className="w-7 h-7 rounded-full bg-cyan-600/20 border border-cyan-500/30 flex items-center justify-center text-cyan-500 text-xs font-bold flex-shrink-0">{i + 1}</div>',
'                    {i < result.roadmap.length - 1 && <div className="w-px flex-1 bg-cyan-500/20 mt-1" />}',
'                  </div>',
'                  <div className="pb-2">',
'                    <div className="text-cyan-500 text-xs font-medium mb-0.5">{r.week}</div>',
'                    <div className="text-slate-800 dark:text-white font-medium text-sm mb-0.5">{r.task}</div>',
'                    <div className="text-slate-400 text-xs">{r.resources}</div>',
'                  </div>',
'                </div>',
'              ))}',
'            </div>',
'            <div className="bg-amber-500/5 border border-amber-500/20 rounded-2xl p-4">',
'              <h3 className="text-amber-500 font-semibold mb-3 text-xs uppercase tracking-wider">ATS Tips</h3>',
'              {(result.ats_tips || []).map((t, i) => <p key={i} className="text-slate-600 dark:text-slate-300 text-sm mb-2">- {t}</p>)}',
'            </div>',
'            <div className="flex gap-3">',
'              <button onClick={() => { setResult(null); setText(""); setRole(""); }} className="flex-1 border border-slate-200 dark:border-white/10 hover:border-cyan-500/50 text-slate-600 dark:text-slate-300 font-medium py-3 rounded-xl text-sm transition-all">Analyze Another</button>',
'              <button onClick={downloadReport} className="flex-1 bg-cyan-600 hover:bg-cyan-500 text-white font-medium py-3 rounded-xl text-sm transition-all">Download Report</button>',
'            </div>',
'          </div>',
'        )}',
'      </div>',
'    </AppShell>',
'  );',
'}',
].join("\n");

fs.writeFileSync(
  "C:/Users/Dell/Desktop/campus Os/2026-04-20-you-are-a-senior-full-stack-2/apps/web/src/app/resume-checker/page.tsx",
  code,
  "utf8"
);
console.log("Done!");
