const fs = require("fs");
const base = "C:/Users/Dell/Desktop/campus Os/2026-04-20-you-are-a-senior-full-stack-2/apps/web/src";

// 1. Auth utility
const authCode = [
'// Simple localStorage-based auth — no backend needed',
'',
'export interface UserData {',
'  id: string;',
'  fullName: string;',
'  email: string;',
'  collegeName: string;',
'  course: string;',
'  graduationYear: number;',
'  resumeScore?: number;',
'  resumeVerdict?: string;',
'  resumeStrengths?: string[];',
'  resumeMissing?: string[];',
'  lastAnalyzed?: string;',
'}',
'',
'export function saveUser(user: UserData) {',
'  localStorage.setItem("campusos_user", JSON.stringify(user));',
'}',
'',
'export function getUser(): UserData | null {',
'  try {',
'    const raw = localStorage.getItem("campusos_user");',
'    return raw ? JSON.parse(raw) : null;',
'  } catch { return null; }',
'}',
'',
'export function logoutUser() {',
'  localStorage.removeItem("campusos_user");',
'}',
'',
'export function isLoggedIn(): boolean {',
'  return !!getUser();',
'}',
'',
'export function getAllUsers(): UserData[] {',
'  try {',
'    const raw = localStorage.getItem("campusos_all_users");',
'    return raw ? JSON.parse(raw) : [];',
'  } catch { return []; }',
'}',
'',
'export function registerUser(data: Omit<UserData, "id">): UserData {',
'  const users = getAllUsers();',
'  const exists = users.find(u => u.email === data.email);',
'  if (exists) throw new Error("Email already registered. Please login.");',
'  const user: UserData = { ...data, id: "user_" + Date.now() };',
'  users.push(user);',
'  localStorage.setItem("campusos_all_users", JSON.stringify(users));',
'  saveUser(user);',
'  return user;',
'}',
'',
'export function loginUser(email: string, password: string): UserData {',
'  const users = getAllUsers();',
'  const passwords = JSON.parse(localStorage.getItem("campusos_passwords") || "{}");',
'  const user = users.find(u => u.email === email);',
'  if (!user) throw new Error("No account found with this email. Please signup first.");',
'  if (passwords[email] && passwords[email] !== password) throw new Error("Incorrect password.");',
'  saveUser(user);',
'  return user;',
'}',
'',
'export function registerUserWithPassword(data: Omit<UserData, "id">, password: string): UserData {',
'  const user = registerUser(data);',
'  const passwords = JSON.parse(localStorage.getItem("campusos_passwords") || "{}");',
'  passwords[data.email] = password;',
'  localStorage.setItem("campusos_passwords", JSON.stringify(passwords));',
'  return user;',
'}',
'',
'export function updateUserResume(resumeData: Partial<UserData>) {',
'  const user = getUser();',
'  if (!user) return;',
'  const updated = { ...user, ...resumeData, lastAnalyzed: new Date().toLocaleDateString() };',
'  saveUser(updated);',
'  const users = getAllUsers();',
'  const idx = users.findIndex(u => u.id === user.id);',
'  if (idx >= 0) { users[idx] = updated; localStorage.setItem("campusos_all_users", JSON.stringify(users)); }',
'  return updated;',
'}',
].join("\n");

fs.writeFileSync(base + "/lib/auth.ts", authCode, "utf8");
console.log("auth.ts created!");
