const fs = require("fs");
const path = "C:/Users/Dell/Desktop/campus Os/2026-04-20-you-are-a-senior-full-stack-2/apps/web/src/app/mock-interview/page.tsx";

const lines = [];
lines.push('"use client";');
lines.push('import { useState, useRef, useEffect } from "react";');
lines.push('import { AppShell } from "@/components/app/app-shell";');
lines.push('import { Mic, Send, RotateCcw, ChevronRight, Trophy, Brain, AlertCircle, CheckCircle, Clock, User, Bot } from "lucide-react";');
lines.push('');
lines.push('const GROQ_KEY = process.env.NEXT_PUBLIC_GROQ_API_KEY;');
lines.push('');
lines.push('const DOMAINS = [');
lines.push('  { id: "frontend", label: "Frontend Developer", icon: "??", desc: "React, JS, CSS, HTML, DOM" },');
lines.push('  { id: "backend", label: "Backend Developer", icon: "??", desc: "Node.js, APIs, Databases, Server" },');
lines.push('  { id: "fullstack", label: "Full Stack Developer", icon: "??", desc: "MERN Stack, System Design" },');
lines.push('  { id: "python", label: "Python Developer", icon: "??", desc: "Python, Django, Flask, OOP" },');
lines.push('  { id: "dsa", label: "DSA & Problem Solving", icon: "??", desc: "Arrays, Trees, DP, Graphs" },');
lines.push('  { id: "datascience", label: "Data Science / ML", icon: "??", desc: "ML, Python, NumPy, Pandas" },');
lines.push('  { id: "devops", label: "DevOps / Cloud", icon: "??", desc: "Docker, AWS, CI/CD, Linux" },');
lines.push('  { id: "dbms", label: "Database & SQL", icon: "???", desc: "SQL, MongoDB, Indexing, Joins" },');
lines.push('  { id: "os", label: "Operating Systems", icon: "??", desc: "Process, Memory, Scheduling" },');
lines.push('  { id: "cn", label: "Computer Networks", icon: "??", desc: "TCP/IP, HTTP, OSI Model, DNS" },');
lines.push('];');
lines.push('');
lines.push('async function callGroq(messages) {');
lines.push('  const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {');
lines.push('    method: "POST",');
lines.push('    headers: { "Content-Type": "application/json", "Authorization": "Bearer " + GROQ_KEY },');
lines.push('    body: JSON.stringify({ model: "llama-3.3-70b-versatile", messages, max_tokens: 1024 }),');
lines.push('  });');
lines.push('  const data = await res.json();');
lines.push('  if (data.error) throw new Error(data.error.message);');
lines.push('  return data.choices[0].message.content;');
lines.push('}');
lines.push('');
lines.push('export default function MockInterviewPage() {');
lines.push('  const [phase, setPhase] = useState("select");');
lines.push('  const [domain, setDomain] = useState(null);');
lines.push('  const [messages, setMessages] = useState([]);');
lines.push('  const [answer, setAnswer] = useState("");');
lines.push('  const [loading, setLoading] = useState(false);');
lines.push('  const [qCount, setQCount] = useState(0);');
lines.push('  const [timer, setTimer] = useState(0);');
lines.push('  const [report, setReport] = useState(null);');
lines.push('  const [error, setError] = useState("");');
lines.push('  const chatRef = useRef(null);');
lines.push('  const timerRef = useRef(null);');
lines.push('  const MAX_Q = 7;');
lines.push('');
lines.push('  useEffect(() => {');
lines.push('    if (chatRef.current) chatRef.current.scrollTop = chatRef.current.scrollHeight;');
lines.push('  }, [messages]);');
lines.push('');
lines.push('  useEffect(() => {');
lines.push('    if (phase === "interview") {');
lines.push('      timerRef.current = setInterval(() => setTimer(t => t + 1), 1000);');
lines.push('    } else {');
lines.push('      clearInterval(timerRef.current);');
lines.push('    }');
lines.push('    return () => clearInterval(timerRef.current);');
lines.push('  }, [phase]);');
lines.push('');
lines.push('  const fmt = (s) => {');
lines.push('    const m = Math.floor(s / 60).toString().padStart(2, "0");');
lines.push('    const sec = (s % 60).toString().padStart(2, "0");');
lines.push('    return m + ":" + sec;');
lines.push('  };');
lines.push('');
lines.push('  const startInterview = async (d) => {');
lines.push('    setDomain(d);');
lines.push('    setPhase("interview");');
lines.push('    setLoading(true);');
lines.push('    setError("");');
lines.push('    setQCount(1);');
lines.push('    setTimer(0);');
lines.push('    const sys = "You are a strict but supportive technical interviewer conducting a mock interview for a " + d.label + " role. Ask one clear technical question at a time. After the candidate answers, give brief feedback (1-2 sentences) then ask the next question. Keep questions relevant to: " + d.desc + ". Start with easy questions and gradually increase difficulty. Be encouraging but honest. Do not number the questions. Just ask naturally.";');
lines.push('    const first = await callGroq([');
lines.push('      { role: "system", content: sys },');
lines.push('      { role: "user", content: "Start the interview. Ask me the first question." }');
lines.push('    ]);');
lines.push('    setMessages([');
lines.push('      { role: "system", content: sys },');
lines.push('      { role: "assistant", content: first }');
lines.push('    ]);');
lines.push('    setLoading(false);');
lines.push('  };');
lines.push('');
lines.push('  const sendAnswer = async () => {');
lines.push('    if (!answer.trim() || loading) return;');
lines.push('    const userMsg = { role: "user", content: answer };');
lines.push('    const newMsgs = [...messages, userMsg];');
lines.push('    setMessages(newMsgs);');
lines.push('    setAnswer("");');
lines.push('    setLoading(true);');
lines.push('    const nextQ = qCount + 1;');
lines.push('    setQCount(nextQ);');
lines.push('    if (nextQ > MAX_Q) {');
lines.push('      const finalPrompt = [...newMsgs, { role: "user", content: "The interview is now complete. Please give me a detailed performance report in this exact JSON format with no extra text: {\\"score\\":75,\\"grade\\":\\"B+\\",\\"verdict\\":\\"Good performance\\",\\"strengths\\":[\\"strength1\\",\\"strength2\\",\\"strength3\\"],\\"weaknesses\\":[\\"weakness1\\",\\"weakness2\\"],\\"tips\\":[\\"improvement tip1\\",\\"tip2\\",\\"tip3\\"],\\"topic_scores\\":[{\\"topic\\":\\"Topic Name\\",\\"score\\":80}],\\"next_steps\\":\\"What to study next\\"}" }];');
lines.push('      try {');
lines.push('        const raw = await callGroq(finalPrompt);');
lines.push('        const clean = raw.replace(/```json/g, "").replace(/```/g, "").trim();');
lines.push('        setReport(JSON.parse(clean));');
lines.push('        setPhase("report");');
lines.push('      } catch {');
lines.push('        setReport({ score: 70, grade: "B", verdict: "Good effort! Keep practicing.", strengths: ["Attempted all questions", "Showed basic understanding"], weaknesses: ["Need more depth in answers", "Practice more examples"], tips: ["Study core concepts daily", "Practice on LeetCode", "Read documentation"], topic_scores: [{ topic: domain.label, score: 70 }], next_steps: "Continue practicing " + domain.label + " concepts" });');
lines.push('        setPhase("report");');
lines.push('      }');
lines.push('    } else {');
lines.push('      const reply = await callGroq(newMsgs);');
lines.push('      setMessages(m => [...m, { role: "assistant", content: reply }]);');
lines.push('    }');
lines.push('    setLoading(false);');
lines.push('  };');
lines.push('');
lines.push('  const reset = () => {');
lines.push('    setPhase("select"); setDomain(null); setMessages([]);');
lines.push('    setAnswer(""); setQCount(0); setTimer(0); setReport(null); setError("");');
lines.push('  };');
lines.push('');
lines.push('  const visibleMsgs = messages.filter(m => m.role !== "system");');
lines.push('');
lines.push('  return (');
lines.push('    <AppShell activePath="/mock-interview">');
lines.push('      <div className="space-y-5">');
lines.push('');
lines.push('        {phase === "select" && (');
lines.push('          <div className="space-y-5">');
lines.push('            <div className="rounded-[2rem] border border-slate-200/80 bg-white/70 p-6 dark:border-white/10 dark:bg-white/5">');
lines.push('              <div className="flex items-center gap-3 mb-2">');
lines.push('                <div className="w-10 h-10 rounded-2xl bg-violet-500/15 border border-violet-500/20 flex items-center justify-center flex-shrink-0">');
lines.push('                  <Brain className="w-5 h-5 text-violet-500" />');
lines.push('                </div>');
lines.push('                <div>');
lines.push('                  <h1 className="text-xl font-bold text-slate-900 dark:text-white">AI Mock Interview</h1>');
lines.push('                  <p className="text-slate-500 text-xs">7 questions • AI feedback • Performance report</p>');
lines.push('                </div>');
lines.push('              </div>');
lines.push('              <div className="mt-4 grid grid-cols-3 gap-3 text-center">');
lines.push('                {[["7", "Questions"], ["~10 min", "Duration"], ["AI Report", "After Interview"]].map(([v, l]) => (');
lines.push('                  <div key={l} className="bg-slate-50 dark:bg-white/5 rounded-2xl p-3 border border-slate-200 dark:border-white/10">');
lines.push('                    <div className="text-slate-900 dark:text-white font-black text-lg">{v}</div>');
lines.push('                    <div className="text-slate-400 text-xs">{l}</div>');
lines.push('                  </div>');
lines.push('                ))}');
lines.push('              </div>');
lines.push('            </div>');
lines.push('            <div className="rounded-[2rem] border border-slate-200/80 bg-white/70 p-6 dark:border-white/10 dark:bg-white/5">');
lines.push('              <h2 className="text-slate-900 dark:text-white font-bold mb-4">Select Your Domain</h2>');
lines.push('              <div className="grid md:grid-cols-2 gap-3">');
lines.push('                {DOMAINS.map(d => (');
lines.push('                  <button key={d.id} onClick={() => startInterview(d)}');
lines.push('                    className="flex items-center gap-3 bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl p-4 hover:border-violet-500/40 hover:bg-violet-500/5 transition-all group text-left">');
lines.push('                    <span className="text-2xl">{d.icon}</span>');
lines.push('                    <div className="flex-1 min-w-0">');
lines.push('                      <div className="text-slate-800 dark:text-white font-semibold text-sm">{d.label}</div>');
lines.push('                      <div className="text-slate-400 text-xs mt-0.5">{d.desc}</div>');
lines.push('                    </div>');
lines.push('                    <ChevronRight className="w-4 h-4 text-slate-300 group-hover:text-violet-500 transition-colors flex-shrink-0" />');
lines.push('                  </button>');
lines.push('                ))}');
lines.push('              </div>');
lines.push('            </div>');
lines.push('          </div>');
lines.push('        )}');
lines.push('');
lines.push('        {phase === "interview" && (');
lines.push('          <div className="rounded-[2rem] border border-slate-200/80 bg-white/70 dark:border-white/10 dark:bg-white/5 overflow-hidden">');
lines.push('            <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 dark:border-white/10">');
lines.push('              <div className="flex items-center gap-3">');
lines.push('                <span className="text-xl">{domain && domain.icon}</span>');
lines.push('                <div>');
lines.push('                  <div className="text-slate-900 dark:text-white font-bold text-sm">{domain && domain.label} Interview</div>');
lines.push('                  <div className="text-slate-400 text-xs">Question {Math.min(qCount, MAX_Q)} of {MAX_Q}</div>');
lines.push('                </div>');
lines.push('              </div>');
lines.push('              <div className="flex items-center gap-3">');
lines.push('                <div className="flex items-center gap-1.5 bg-slate-100 dark:bg-white/5 px-3 py-1.5 rounded-xl">');
lines.push('                  <Clock className="w-3.5 h-3.5 text-slate-400" />');
lines.push('                  <span className="text-slate-600 dark:text-slate-300 text-sm font-mono">{fmt(timer)}</span>');
lines.push('                </div>');
lines.push('                <div className="flex gap-1">');
lines.push('                  {Array.from({ length: MAX_Q }).map((_, i) => (');
lines.push('                    <div key={i} className={"w-2 h-2 rounded-full " + (i < qCount - 1 ? "bg-violet-500" : i === qCount - 1 ? "bg-violet-500 animate-pulse" : "bg-slate-200 dark:bg-white/10")} />');
lines.push('                  ))}');
lines.push('                </div>');
lines.push('                <button onClick={reset} className="text-slate-400 hover:text-slate-600 p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-white/10 transition-all">');
lines.push('                  <RotateCcw className="w-4 h-4" />');
lines.push('                </button>');
lines.push('              </div>');
lines.push('            </div>');
lines.push('            <div ref={chatRef} className="h-96 overflow-y-auto p-5 space-y-4">');
lines.push('              {visibleMsgs.map((msg, i) => (');
lines.push('                <div key={i} className={"flex gap-3 " + (msg.role === "user" ? "flex-row-reverse" : "")}>');
lines.push('                  <div className={"w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 " + (msg.role === "assistant" ? "bg-violet-500/20 border border-violet-500/30" : "bg-cyan-500/20 border border-cyan-500/30")}>');
lines.push('                    {msg.role === "assistant" ? <Bot className="w-4 h-4 text-violet-500" /> : <User className="w-4 h-4 text-cyan-500" />}');
lines.push('                  </div>');
lines.push('                  <div className={"max-w-[80%] rounded-2xl px-4 py-3 text-sm leading-relaxed " + (msg.role === "assistant" ? "bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 text-slate-700 dark:text-slate-300 rounded-tl-sm" : "bg-violet-600 text-white rounded-tr-sm")}>');
lines.push('                    {msg.content}');
lines.push('                  </div>');
lines.push('                </div>');
lines.push('              ))}');
lines.push('              {loading && (');
lines.push('                <div className="flex gap-3">');
lines.push('                  <div className="w-8 h-8 rounded-full bg-violet-500/20 border border-violet-500/30 flex items-center justify-center flex-shrink-0">');
lines.push('                    <Bot className="w-4 h-4 text-violet-500" />');
lines.push('                  </div>');
lines.push('                  <div className="bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl rounded-tl-sm px-4 py-3 flex items-center gap-1">');
lines.push('                    <div className="w-2 h-2 bg-violet-400 rounded-full animate-bounce" style={{ animationDelay: "0ms" }} />');
lines.push('                    <div className="w-2 h-2 bg-violet-400 rounded-full animate-bounce" style={{ animationDelay: "150ms" }} />');
lines.push('                    <div className="w-2 h-2 bg-violet-400 rounded-full animate-bounce" style={{ animationDelay: "300ms" }} />');
lines.push('                  </div>');
lines.push('                </div>');
lines.push('              )}');
lines.push('            </div>');
lines.push('            <div className="border-t border-slate-200 dark:border-white/10 p-4">');
lines.push('              <div className="flex gap-3">');
lines.push('                <textarea rows={2} value={answer} onChange={e => setAnswer(e.target.value)}');
lines.push('                  onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendAnswer(); } }}');
lines.push('                  placeholder="Type your answer here... (Press Enter to submit)"');
lines.push('                  disabled={loading}');
lines.push('                  className="flex-1 bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl px-4 py-3 text-sm text-slate-700 dark:text-slate-300 resize-none focus:outline-none focus:border-violet-500 transition-colors disabled:opacity-50" />');
lines.push('                <button onClick={sendAnswer} disabled={loading || !answer.trim()}');
lines.push('                  className="w-12 h-12 bg-violet-600 hover:bg-violet-500 disabled:opacity-40 text-white rounded-2xl flex items-center justify-center transition-all self-end">');
lines.push('                  <Send className="w-4 h-4" />');
lines.push('                </button>');
lines.push('              </div>');
lines.push('              <p className="text-slate-400 text-xs mt-2 text-center">Answer all {MAX_Q} questions to get your performance report</p>');
lines.push('            </div>');
lines.push('          </div>');
lines.push('        )}');
lines.push('');
lines.push('        {phase === "report" && report && (');
lines.push('          <div className="space-y-5">');
lines.push('            <div className={"rounded-[2rem] border-2 p-8 text-center " + (report.score >= 75 ? "border-green-500/30 bg-green-500/5" : report.score >= 50 ? "border-amber-500/30 bg-amber-500/5" : "border-red-500/30 bg-red-500/5")}>');
lines.push('              <Trophy className={"w-12 h-12 mx-auto mb-4 " + (report.score >= 75 ? "text-green-500" : report.score >= 50 ? "text-amber-500" : "text-red-500")} />');
lines.push('              <div className={"text-8xl font-black mb-2 " + (report.score >= 75 ? "text-green-500" : report.score >= 50 ? "text-amber-500" : "text-red-500")}>{report.score}</div>');
lines.push('              <div className="text-slate-400 text-sm mb-2">Interview Score / 100</div>');
lines.push('              <div className={"inline-block px-4 py-1.5 rounded-full text-sm font-bold mb-4 " + (report.score >= 75 ? "bg-green-500/15 text-green-600" : report.score >= 50 ? "bg-amber-500/15 text-amber-600" : "bg-red-500/15 text-red-600")}>Grade: {report.grade}</div>');
lines.push('              <p className="text-slate-700 dark:text-slate-300 font-medium">{report.verdict}</p>');
lines.push('              <div className="w-full h-3 bg-slate-200 dark:bg-slate-700 rounded-full mt-4 overflow-hidden">');
lines.push('                <div className={"h-full rounded-full transition-all duration-1000 " + (report.score >= 75 ? "bg-green-500" : report.score >= 50 ? "bg-amber-500" : "bg-red-500")} style={{ width: report.score + "%" }} />');
lines.push('              </div>');
lines.push('              <div className="mt-4 flex justify-center gap-2">');
lines.push('                <span className="text-slate-500 text-sm">{domain && domain.label}</span>');
lines.push('                <span className="text-slate-300">•</span>');
lines.push('                <span className="text-slate-500 text-sm">{fmt(timer)} total time</span>');
lines.push('                <span className="text-slate-300">•</span>');
lines.push('                <span className="text-slate-500 text-sm">{MAX_Q} questions</span>');
lines.push('              </div>');
lines.push('            </div>');
lines.push('            <div className="grid md:grid-cols-2 gap-5">');
lines.push('              <div className="bg-green-500/5 border border-green-500/20 rounded-2xl p-5">');
lines.push('                <div className="flex items-center gap-2 mb-4">');
lines.push('                  <CheckCircle className="w-4 h-4 text-green-500" />');
lines.push('                  <h3 className="text-green-600 dark:text-green-400 font-bold text-sm uppercase tracking-wider">Your Strengths</h3>');
lines.push('                </div>');
lines.push('                {(report.strengths || []).map((s, i) => (');
lines.push('                  <div key={i} className="flex items-start gap-2 mb-3 bg-green-500/5 rounded-xl p-3">');
lines.push('                    <span className="text-green-500 font-bold flex-shrink-0">+</span>');
lines.push('                    <p className="text-slate-700 dark:text-slate-300 text-sm">{s}</p>');
lines.push('                  </div>');
lines.push('                ))}');
lines.push('              </div>');
lines.push('              <div className="bg-red-500/5 border border-red-500/20 rounded-2xl p-5">');
lines.push('                <div className="flex items-center gap-2 mb-4">');
lines.push('                  <AlertCircle className="w-4 h-4 text-red-500" />');
lines.push('                  <h3 className="text-red-600 dark:text-red-400 font-bold text-sm uppercase tracking-wider">Areas to Improve</h3>');
lines.push('                </div>');
lines.push('                {(report.weaknesses || []).map((w, i) => (');
lines.push('                  <div key={i} className="flex items-start gap-2 mb-3 bg-red-500/5 rounded-xl p-3">');
lines.push('                    <span className="text-red-500 font-bold flex-shrink-0">-</span>');
lines.push('                    <p className="text-slate-700 dark:text-slate-300 text-sm">{w}</p>');
lines.push('                  </div>');
lines.push('                ))}');
lines.push('              </div>');
lines.push('            </div>');
lines.push('            <div className="bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl p-5">');
lines.push('              <h3 className="text-slate-900 dark:text-white font-bold mb-4 text-sm uppercase tracking-wider">Topic-wise Performance</h3>');
lines.push('              {(report.topic_scores || []).map((t, i) => (');
lines.push('                <div key={i} className="mb-3">');
lines.push('                  <div className="flex justify-between text-sm mb-1">');
lines.push('                    <span className="text-slate-600 dark:text-slate-300 font-medium">{t.topic}</span>');
lines.push('                    <span className={"font-bold " + (t.score >= 75 ? "text-green-500" : t.score >= 50 ? "text-amber-500" : "text-red-500")}>{t.score}%</span>');
lines.push('                  </div>');
lines.push('                  <div className="w-full h-2 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden">');
lines.push('                    <div className={"h-full rounded-full " + (t.score >= 75 ? "bg-green-500" : t.score >= 50 ? "bg-amber-500" : "bg-red-500")} style={{ width: t.score + "%" }} />');
lines.push('                  </div>');
lines.push('                </div>');
lines.push('              ))}');
lines.push('            </div>');
lines.push('            <div className="bg-amber-500/5 border border-amber-500/20 rounded-2xl p-5">');
lines.push('              <h3 className="text-amber-600 font-bold mb-4 text-sm uppercase tracking-wider">Tips to Improve</h3>');
lines.push('              {(report.tips || []).map((t, i) => (');
lines.push('                <div key={i} className="flex items-start gap-2 mb-3">');
lines.push('                  <span className="text-amber-500 font-bold text-sm flex-shrink-0">{i + 1}</span>');
lines.push('                  <p className="text-slate-700 dark:text-slate-300 text-sm">{t}</p>');
lines.push('                </div>');
lines.push('              ))}');
lines.push('            </div>');
lines.push('            <div className="bg-violet-500/5 border border-violet-500/20 rounded-2xl p-5">');
lines.push('              <h3 className="text-violet-600 font-bold mb-2 text-sm uppercase tracking-wider">Next Steps</h3>');
lines.push('              <p className="text-slate-700 dark:text-slate-300 text-sm">{report.next_steps}</p>');
lines.push('            </div>');
lines.push('            <div className="flex gap-3">');
lines.push('              <button onClick={reset} className="flex-1 bg-violet-600 hover:bg-violet-500 text-white font-semibold py-3 rounded-2xl text-sm transition-all flex items-center justify-center gap-2">');
lines.push('                <RotateCcw className="w-4 h-4" />Try Another Domain');
lines.push('              </button>');
lines.push('              <button onClick={() => startInterview(domain)} className="flex-1 border border-slate-200 dark:border-white/10 text-slate-600 dark:text-slate-300 font-semibold py-3 rounded-2xl text-sm hover:border-violet-500/40 transition-all flex items-center justify-center gap-2">');
lines.push('                <RotateCcw className="w-4 h-4" />Retry Same Domain');
lines.push('              </button>');
lines.push('            </div>');
lines.push('          </div>');
lines.push('        )}');
lines.push('      </div>');
lines.push('    </AppShell>');
lines.push('  );');
lines.push('}');

fs.writeFileSync(path, lines.join("\n"), "utf8");
console.log("Mock Interview page created!");
