const fs = require("fs");
const path = "C:/Users/Dell/Desktop/campus Os/2026-04-20-you-are-a-senior-full-stack-2/apps/web/src/components/app/ai-chatbot.tsx";

const lines = [];
lines.push('"use client";');
lines.push('import { useState, useRef, useEffect } from "react";');
lines.push('import { MessageCircle, X, Send, Bot, User, Minimize2, Maximize2 } from "lucide-react";');
lines.push('');
lines.push('const GROQ_KEY = process.env.NEXT_PUBLIC_GROQ_API_KEY;');
lines.push('');
lines.push('const SYSTEM_MSG = "You are CampusOS Study Assistant, a helpful AI tutor for computer science students. Help with DSA, programming, DBMS, OS, networking, web development, career advice, and placement preparation. Keep answers concise, clear and student-friendly. Use simple language. If explaining code, use proper formatting.";');
lines.push('');
lines.push('const SUGGESTIONS = [');
lines.push('  "Explain Big O notation",');
lines.push('  "What is a binary search tree?",');
lines.push('  "How does TCP/IP work?",');
lines.push('  "Explain React hooks",');
lines.push('  "What is normalization in DBMS?",');
lines.push('  "How to prepare for placements?",');
lines.push('];');
lines.push('');
lines.push('async function askGroq(messages) {');
lines.push('  const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {');
lines.push('    method: "POST",');
lines.push('    headers: { "Content-Type": "application/json", "Authorization": "Bearer " + GROQ_KEY },');
lines.push('    body: JSON.stringify({ model: "llama-3.3-70b-versatile", messages: [{ role: "system", content: SYSTEM_MSG }, ...messages], max_tokens: 512 }),');
lines.push('  });');
lines.push('  const data = await res.json();');
lines.push('  if (data.error) throw new Error(data.error.message);');
lines.push('  return data.choices[0].message.content;');
lines.push('}');
lines.push('');
lines.push('export function AIChatbot() {');
lines.push('  const [open, setOpen] = useState(false);');
lines.push('  const [minimized, setMinimized] = useState(false);');
lines.push('  const [messages, setMessages] = useState([]);');
lines.push('  const [input, setInput] = useState("");');
lines.push('  const [loading, setLoading] = useState(false);');
lines.push('  const [pulse, setPulse] = useState(true);');
lines.push('  const chatRef = useRef(null);');
lines.push('');
lines.push('  useEffect(() => {');
lines.push('    if (chatRef.current) chatRef.current.scrollTop = chatRef.current.scrollHeight;');
lines.push('  }, [messages, open]);');
lines.push('');
lines.push('  useEffect(() => {');
lines.push('    const t = setTimeout(() => setPulse(false), 5000);');
lines.push('    return () => clearTimeout(t);');
lines.push('  }, []);');
lines.push('');
lines.push('  const send = async (text) => {');
lines.push('    const q = (text || input).trim();');
lines.push('    if (!q || loading) return;');
lines.push('    setInput("");');
lines.push('    const newMsgs = [...messages, { role: "user", content: q }];');
lines.push('    setMessages(newMsgs);');
lines.push('    setLoading(true);');
lines.push('    try {');
lines.push('      const reply = await askGroq(newMsgs);');
lines.push('      setMessages(m => [...m, { role: "assistant", content: reply }]);');
lines.push('    } catch {');
lines.push('      setMessages(m => [...m, { role: "assistant", content: "Sorry, I am having trouble connecting. Please check your API key and try again." }]);');
lines.push('    }');
lines.push('    setLoading(false);');
lines.push('  };');
lines.push('');
lines.push('  return (');
lines.push('    <div className="fixed bottom-6 right-6 z-50 flex flex-col items-end gap-3">');
lines.push('');
lines.push('      {open && !minimized && (');
lines.push('        <div className="w-80 md:w-96 bg-white dark:bg-[#0f172a] border border-slate-200 dark:border-white/10 rounded-[1.8rem] shadow-2xl shadow-slate-900/20 flex flex-col overflow-hidden" style={{ height: "520px", animation: "slideUp 0.3s ease-out" }}>');
lines.push('          <style>{`@keyframes slideUp { from { opacity: 0; transform: translateY(20px) scale(0.95); } to { opacity: 1; transform: translateY(0) scale(1); } }`}</style>');
lines.push('          <div className="bg-gradient-to-r from-violet-600 to-cyan-600 p-4 flex items-center justify-between flex-shrink-0">');
lines.push('            <div className="flex items-center gap-3">');
lines.push('              <div className="w-9 h-9 rounded-xl bg-white/20 flex items-center justify-center">');
lines.push('                <Bot className="w-5 h-5 text-white" />');
lines.push('              </div>');
lines.push('              <div>');
lines.push('                <p className="text-white font-bold text-sm">CampusOS AI</p>');
lines.push('                <div className="flex items-center gap-1.5">');
lines.push('                  <div className="w-1.5 h-1.5 bg-green-400 rounded-full animate-pulse" />');
lines.push('                  <p className="text-white/70 text-xs">Study Assistant • Online</p>');
lines.push('                </div>');
lines.push('              </div>');
lines.push('            </div>');
lines.push('            <div className="flex items-center gap-2">');
lines.push('              <button onClick={() => setMinimized(true)} className="text-white/70 hover:text-white p-1.5 rounded-lg hover:bg-white/10 transition-all">');
lines.push('                <Minimize2 className="w-4 h-4" />');
lines.push('              </button>');
lines.push('              <button onClick={() => setOpen(false)} className="text-white/70 hover:text-white p-1.5 rounded-lg hover:bg-white/10 transition-all">');
lines.push('                <X className="w-4 h-4" />');
lines.push('              </button>');
lines.push('            </div>');
lines.push('          </div>');
lines.push('');
lines.push('          <div ref={chatRef} className="flex-1 overflow-y-auto p-4 space-y-3">');
lines.push('            {messages.length === 0 && (');
lines.push('              <div className="h-full flex flex-col justify-center">');
lines.push('                <div className="text-center mb-4">');
lines.push('                  <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-violet-500/20 to-cyan-500/20 border border-violet-500/20 flex items-center justify-center mx-auto mb-3">');
lines.push('                    <Bot className="w-7 h-7 text-violet-500" />');
lines.push('                  </div>');
lines.push('                  <p className="text-slate-800 dark:text-white font-bold text-sm">Hey! I am your AI Study Assistant</p>');
lines.push('                  <p className="text-slate-400 text-xs mt-1">Ask me anything about CS, coding or placements</p>');
lines.push('                </div>');
lines.push('                <div className="grid grid-cols-2 gap-2">');
lines.push('                  {SUGGESTIONS.map(s => (');
lines.push('                    <button key={s} onClick={() => send(s)}');
lines.push('                      className="text-left text-xs bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-xl p-2.5 text-slate-600 dark:text-slate-400 hover:border-violet-500/30 hover:text-violet-600 hover:bg-violet-500/5 transition-all">');
lines.push('                      {s}');
lines.push('                    </button>');
lines.push('                  ))}');
lines.push('                </div>');
lines.push('              </div>');
lines.push('            )}');
lines.push('            {messages.map((msg, i) => (');
lines.push('              <div key={i} className={"flex gap-2 " + (msg.role === "user" ? "flex-row-reverse" : "")}>');
lines.push('                <div className={"w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0 mt-1 " + (msg.role === "assistant" ? "bg-violet-500/20" : "bg-cyan-500/20")}>');
lines.push('                  {msg.role === "assistant" ? <Bot className="w-3.5 h-3.5 text-violet-500" /> : <User className="w-3.5 h-3.5 text-cyan-500" />}');
lines.push('                </div>');
lines.push('                <div className={"max-w-[85%] rounded-2xl px-3.5 py-2.5 text-xs leading-relaxed " + (msg.role === "assistant" ? "bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 text-slate-700 dark:text-slate-300 rounded-tl-sm" : "bg-gradient-to-br from-violet-600 to-violet-700 text-white rounded-tr-sm")}>');
lines.push('                  <pre className="whitespace-pre-wrap font-sans">{msg.content}</pre>');
lines.push('                </div>');
lines.push('              </div>');
lines.push('            ))}');
lines.push('            {loading && (');
lines.push('              <div className="flex gap-2">');
lines.push('                <div className="w-7 h-7 rounded-full bg-violet-500/20 flex items-center justify-center flex-shrink-0">');
lines.push('                  <Bot className="w-3.5 h-3.5 text-violet-500" />');
lines.push('                </div>');
lines.push('                <div className="bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl rounded-tl-sm px-3.5 py-3 flex items-center gap-1">');
lines.push('                  <div className="w-1.5 h-1.5 bg-violet-400 rounded-full animate-bounce" style={{ animationDelay: "0ms" }} />');
lines.push('                  <div className="w-1.5 h-1.5 bg-violet-400 rounded-full animate-bounce" style={{ animationDelay: "150ms" }} />');
lines.push('                  <div className="w-1.5 h-1.5 bg-violet-400 rounded-full animate-bounce" style={{ animationDelay: "300ms" }} />');
lines.push('                </div>');
lines.push('              </div>');
lines.push('            )}');
lines.push('          </div>');
lines.push('');
lines.push('          <div className="border-t border-slate-200 dark:border-white/10 p-3 flex-shrink-0">');
lines.push('            <div className="flex gap-2">');
lines.push('              <input value={input} onChange={e => setInput(e.target.value)}');
lines.push('                onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(null); } }}');
lines.push('                placeholder="Ask about DSA, React, SQL..."');
lines.push('                disabled={loading}');
lines.push('                className="flex-1 bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-xl px-3 py-2.5 text-xs text-slate-700 dark:text-slate-300 focus:outline-none focus:border-violet-500 transition-colors disabled:opacity-50" />');
lines.push('              <button onClick={() => send(null)} disabled={loading || !input.trim()}');
lines.push('                className="w-10 h-10 bg-gradient-to-br from-violet-600 to-cyan-600 hover:opacity-90 disabled:opacity-40 text-white rounded-xl flex items-center justify-center transition-all flex-shrink-0">');
lines.push('                <Send className="w-3.5 h-3.5" />');
lines.push('              </button>');
lines.push('            </div>');
lines.push('          </div>');
lines.push('        </div>');
lines.push('      )}');
lines.push('');
lines.push('      {open && minimized && (');
lines.push('        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-white/10 rounded-2xl px-4 py-3 flex items-center gap-3 shadow-lg cursor-pointer" onClick={() => setMinimized(false)}>');
lines.push('          <Bot className="w-4 h-4 text-violet-500" />');
lines.push('          <span className="text-slate-700 dark:text-slate-300 text-sm font-medium">CampusOS AI</span>');
lines.push('          <Maximize2 className="w-3.5 h-3.5 text-slate-400" />');
lines.push('        </div>');
lines.push('      )}');
lines.push('');
lines.push('      <button onClick={() => { setOpen(!open); setMinimized(false); setPulse(false); }}');
lines.push('        className="relative w-14 h-14 bg-gradient-to-br from-violet-600 to-cyan-600 hover:from-violet-500 hover:to-cyan-500 text-white rounded-2xl flex items-center justify-center shadow-2xl shadow-violet-500/40 hover:shadow-violet-500/60 transition-all hover:scale-105 active:scale-95">');
lines.push('        {open ? <X className="w-6 h-6" /> : <MessageCircle className="w-6 h-6" />}');
lines.push('        {!open && messages.length === 0 && pulse && (');
lines.push('          <span className="absolute -top-1 -right-1 w-4 h-4 bg-green-400 rounded-full border-2 border-white dark:border-slate-900 animate-pulse" />');
lines.push('        )}');
lines.push('        {!open && messages.length > 0 && (');
lines.push('          <span className="absolute -top-1 -right-1 w-5 h-5 bg-red-500 rounded-full border-2 border-white dark:border-slate-900 flex items-center justify-center text-xs font-bold">{messages.filter(m => m.role === "assistant").length}</span>');
lines.push('        )}');
lines.push('      </button>');
lines.push('    </div>');
lines.push('  );');
lines.push('}');

fs.writeFileSync(path, lines.join("\n"), "utf8");
console.log("AI Chatbot component created!");
